# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AnnotationExtension Class
#'
#' @field filler 
#' @field relation_chain 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AnnotationExtension <- R6::R6Class(
  'AnnotationExtension',
  public = list(
    `filler` = NULL,
    `relation_chain` = NULL,
    initialize = function(`filler`, `relation_chain`){
      if (!missing(`filler`)) {
        stopifnot(R6::is.R6(`filler`))
        self$`filler` <- `filler`
      }
      if (!missing(`relation_chain`)) {
        stopifnot(is.list(`relation_chain`), length(`relation_chain`) != 0)
        lapply(`relation_chain`, function(x) stopifnot(R6::is.R6(x)))
        self$`relation_chain` <- `relation_chain`
      }
    },
    toJSON = function() {
      AnnotationExtensionObject <- list()
      if (!is.null(self$`filler`)) {
        AnnotationExtensionObject[['filler']] <- self$`filler`$toJSON()
      }
      if (!is.null(self$`relation_chain`)) {
        AnnotationExtensionObject[['relation_chain']] <- lapply(self$`relation_chain`, function(x) x$toJSON())
      }

      AnnotationExtensionObject
    },
    fromJSON = function(AnnotationExtensionJson) {
      AnnotationExtensionObject <- jsonlite::fromJSON(AnnotationExtensionJson)
      if (!is.null(AnnotationExtensionObject$`filler`)) {
        fillerObject <- NamedObject$new()
        fillerObject$fromJSON(jsonlite::toJSON(AnnotationExtensionObject$filler, auto_unbox = TRUE))
        self$`filler` <- fillerObject
      }
      if (!is.null(AnnotationExtensionObject$`relation_chain`)) {
        self$`relation_chain` <- lapply(AnnotationExtensionObject$`relation_chain`, function(x) {
          relation_chainObject <- Relation$new()
          relation_chainObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          relation_chainObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "filler": %s,
           "relation_chain": [%s]
        }',
        self$`filler`$toJSON(),
        lapply(self$`relation_chain`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(AnnotationExtensionJson) {
      AnnotationExtensionObject <- jsonlite::fromJSON(AnnotationExtensionJson)
      NamedObjectObject <- NamedObject$new()
      self$`filler` <- NamedObjectObject$fromJSON(jsonlite::toJSON(AnnotationExtensionObject$filler, auto_unbox = TRUE))
      self$`relation_chain` <- lapply(AnnotationExtensionObject$`relation_chain`, function(x) Relation$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
