# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' APageOfResults Class
#'
#' @field total 
#' @field page 
#' @field pages 
#' @field per_page 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
APageOfResults <- R6::R6Class(
  'APageOfResults',
  public = list(
    `total` = NULL,
    `page` = NULL,
    `pages` = NULL,
    `per_page` = NULL,
    initialize = function(`total`, `page`, `pages`, `per_page`){
      if (!missing(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!missing(`page`)) {
        stopifnot(is.numeric(`page`), length(`page`) == 1)
        self$`page` <- `page`
      }
      if (!missing(`pages`)) {
        stopifnot(is.numeric(`pages`), length(`pages`) == 1)
        self$`pages` <- `pages`
      }
      if (!missing(`per_page`)) {
        stopifnot(is.numeric(`per_page`), length(`per_page`) == 1)
        self$`per_page` <- `per_page`
      }
    },
    toJSON = function() {
      APageOfResultsObject <- list()
      if (!is.null(self$`total`)) {
        APageOfResultsObject[['total']] <- self$`total`
      }
      if (!is.null(self$`page`)) {
        APageOfResultsObject[['page']] <- self$`page`
      }
      if (!is.null(self$`pages`)) {
        APageOfResultsObject[['pages']] <- self$`pages`
      }
      if (!is.null(self$`per_page`)) {
        APageOfResultsObject[['per_page']] <- self$`per_page`
      }

      APageOfResultsObject
    },
    fromJSON = function(APageOfResultsJson) {
      APageOfResultsObject <- jsonlite::fromJSON(APageOfResultsJson)
      if (!is.null(APageOfResultsObject$`total`)) {
        self$`total` <- APageOfResultsObject$`total`
      }
      if (!is.null(APageOfResultsObject$`page`)) {
        self$`page` <- APageOfResultsObject$`page`
      }
      if (!is.null(APageOfResultsObject$`pages`)) {
        self$`pages` <- APageOfResultsObject$`pages`
      }
      if (!is.null(APageOfResultsObject$`per_page`)) {
        self$`per_page` <- APageOfResultsObject$`per_page`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "total": %d,
           "page": %d,
           "pages": %d,
           "per_page": %d
        }',
        self$`total`,
        self$`page`,
        self$`pages`,
        self$`per_page`
      )
    },
    fromJSONString = function(APageOfResultsJson) {
      APageOfResultsObject <- jsonlite::fromJSON(APageOfResultsJson)
      self$`total` <- APageOfResultsObject$`total`
      self$`page` <- APageOfResultsObject$`page`
      self$`pages` <- APageOfResultsObject$`pages`
      self$`per_page` <- APageOfResultsObject$`per_page`
    }
  )
)
