# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AssociationResults Class
#'
#' @field start 
#' @field facet_pivot 
#' @field facet_counts 
#' @field numFound 
#' @field objects 
#' @field associations 
#' @field compact_associations 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AssociationResults <- R6::R6Class(
  'AssociationResults',
  public = list(
    `start` = NULL,
    `facet_pivot` = NULL,
    `facet_counts` = NULL,
    `numFound` = NULL,
    `objects` = NULL,
    `associations` = NULL,
    `compact_associations` = NULL,
    initialize = function(`start`, `facet_pivot`, `facet_counts`, `numFound`, `objects`, `associations`, `compact_associations`){
      if (!missing(`start`)) {
        stopifnot(is.numeric(`start`), length(`start`) == 1)
        self$`start` <- `start`
      }
      if (!missing(`facet_pivot`)) {
        stopifnot(R6::is.R6(`facet_pivot`))
        self$`facet_pivot` <- `facet_pivot`
      }
      if (!missing(`facet_counts`)) {
        stopifnot(R6::is.R6(`facet_counts`))
        self$`facet_counts` <- `facet_counts`
      }
      if (!missing(`numFound`)) {
        stopifnot(is.numeric(`numFound`), length(`numFound`) == 1)
        self$`numFound` <- `numFound`
      }
      if (!missing(`objects`)) {
        stopifnot(is.list(`objects`), length(`objects`) != 0)
        lapply(`objects`, function(x) stopifnot(is.character(x)))
        self$`objects` <- `objects`
      }
      if (!missing(`associations`)) {
        stopifnot(is.list(`associations`), length(`associations`) != 0)
        lapply(`associations`, function(x) stopifnot(R6::is.R6(x)))
        self$`associations` <- `associations`
      }
      if (!missing(`compact_associations`)) {
        stopifnot(is.list(`compact_associations`), length(`compact_associations`) != 0)
        lapply(`compact_associations`, function(x) stopifnot(R6::is.R6(x)))
        self$`compact_associations` <- `compact_associations`
      }
    },
    toJSON = function() {
      AssociationResultsObject <- list()
      if (!is.null(self$`start`)) {
        AssociationResultsObject[['start']] <- self$`start`
      }
      if (!is.null(self$`facet_pivot`)) {
        AssociationResultsObject[['facet_pivot']] <- self$`facet_pivot`$toJSON()
      }
      if (!is.null(self$`facet_counts`)) {
        AssociationResultsObject[['facet_counts']] <- self$`facet_counts`$toJSON()
      }
      if (!is.null(self$`numFound`)) {
        AssociationResultsObject[['numFound']] <- self$`numFound`
      }
      if (!is.null(self$`objects`)) {
        AssociationResultsObject[['objects']] <- self$`objects`
      }
      if (!is.null(self$`associations`)) {
        AssociationResultsObject[['associations']] <- lapply(self$`associations`, function(x) x$toJSON())
      }
      if (!is.null(self$`compact_associations`)) {
        AssociationResultsObject[['compact_associations']] <- lapply(self$`compact_associations`, function(x) x$toJSON())
      }

      AssociationResultsObject
    },
    fromJSON = function(AssociationResultsJson) {
      AssociationResultsObject <- jsonlite::fromJSON(AssociationResultsJson)
      if (!is.null(AssociationResultsObject$`start`)) {
        self$`start` <- AssociationResultsObject$`start`
      }
      # if (!is.null(AssociationResultsObject$`facet_pivot`)) {
      #   facet_pivotObject <- TODO_OBJECT_MAPPING$new()
      #   facet_pivotObject$fromJSON(jsonlite::toJSON(AssociationResultsObject$facet_pivot, auto_unbox = TRUE))
      #   self$`facet_pivot` <- facet_pivotObject
      # }
      # if (!is.null(AssociationResultsObject$`facet_counts`)) {
      #   facet_countsObject <- TODO_OBJECT_MAPPING$new()
      #   facet_countsObject$fromJSON(jsonlite::toJSON(AssociationResultsObject$facet_counts, auto_unbox = TRUE))
      #   self$`facet_counts` <- facet_countsObject
      # }
      if (!is.null(AssociationResultsObject$`numFound`)) {
        self$`numFound` <- AssociationResultsObject$`numFound`
      }
      if (!is.null(AssociationResultsObject$`objects`)) {
        self$`objects` <- AssociationResultsObject$`objects`
      }
      # bug here. During lapply, the names are dropped from associations, so there is nothing for 
      # the fromJSON method in Association.r to access, the names are always null.
      # probably applies to facets as well.
      if (!is.null(AssociationResultsObject$`associations`)) {
        self$`associations` <- lapply(AssociationResultsObject$`associations`, function(x) {
          if (!is.data.frame(x)) x <- data.frame(x)                                         
          associationsObject <- Association$new()
          associationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          associationsObject
        })
      }
      if (!is.null(AssociationResultsObject$`compact_associations`)) {
        self$`compact_associations` <- lapply(AssociationResultsObject$`compact_associations`, function(x) {
          compact_associationsObject <- CompactAssociationSet$new()
          compact_associationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          compact_associationsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "start": %d,
           "facet_pivot": %s,
           "facet_counts": %s,
           "numFound": %d,
           "objects": [%s],
           "associations": [%s],
           "compact_associations": [%s]
        }',
        self$`start`,
        self$`facet_pivot`$toJSON(),
        self$`facet_counts`$toJSON(),
        self$`numFound`,
        lapply(self$`objects`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`associations`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`compact_associations`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(AssociationResultsJson) {
      AssociationResultsObject <- jsonlite::fromJSON(AssociationResultsJson)
      self$`start` <- AssociationResultsObject$`start`
      #TODO_OBJECT_MAPPINGObject <- TODO_OBJECT_MAPPING$new()
      #self$`facet_pivot` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(AssociationResultsObject$facet_pivot, auto_unbox = TRUE))
      #TODO_OBJECT_MAPPINGObject <- TODO_OBJECT_MAPPING$new()
      #self$`facet_counts` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(AssociationResultsObject$facet_counts, auto_unbox = TRUE))
      self$`numFound` <- AssociationResultsObject$`numFound`
      self$`objects` <- AssociationResultsObject$`objects`
      self$`associations` <- lapply(AssociationResultsObject$`associations`, function(x) Association$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`compact_associations` <- lapply(AssociationResultsObject$`compact_associations`, function(x) CompactAssociationSet$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
