# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Association operations
#' @description swagger.Association
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' get_association_by_subject_and_object_category_search Returns list of matching associations
#'
#'
#' get_association_by_subject_category_search Returns list of matching associations
#'
#'
#' get_association_object Returns the association with a given identifier
#'
#'
#' get_association_search Generalized search over complete corpus of associations
#'
#'
#' get_associations_between Returns associations connecting two entities
#'
#'
#' get_associations_from Returns list of matching associations starting from a given subject (source)
#'
#'
#' get_associations_to Returns list of matching associations pointing to a given object (target)
#'
#' }
#'
#' @export
AssociationApi <- R6::R6Class(
  'AssociationApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    get_association_by_subject_and_object_category_search = function(object_category, subject_category, page, subject, object, subject_taxon, evidence, graphize, map_identifiers, fl_excludes_evidence, rows, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`subject`)) {
        queryParams['subject'] <- subject
      }

      if (!missing(`object`)) {
        queryParams['object'] <- object
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`graphize`)) {
        queryParams['graphize'] <- graphize
      }

      if (!missing(`map_identifiers`)) {
        queryParams['map_identifiers'] <- map_identifiers
      }

      if (!missing(`fl_excludes_evidence`)) {
        queryParams['fl_excludes_evidence'] <- fl_excludes_evidence
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      urlPath <- "/association/find/{subject_category}/{object_category}/"
      if (!missing(`object_category`)) {
        urlPath <- gsub(paste0("\\{", "object_category", "\\}"), `object_category`, urlPath)
      }

      if (!missing(`subject_category`)) {
        urlPath <- gsub(paste0("\\{", "subject_category", "\\}"), `subject_category`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_association_by_subject_category_search = function(subject_category, object_category, page, subject, object, subject_taxon, evidence, graphize, map_identifiers, fl_excludes_evidence, rows, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`object_category`)) {
        queryParams['object_category'] <- object_category
      }

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`subject`)) {
        queryParams['subject'] <- subject
      }

      if (!missing(`object`)) {
        queryParams['object'] <- object
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`graphize`)) {
        queryParams['graphize'] <- graphize
      }

      if (!missing(`map_identifiers`)) {
        queryParams['map_identifiers'] <- map_identifiers
      }

      if (!missing(`fl_excludes_evidence`)) {
        queryParams['fl_excludes_evidence'] <- fl_excludes_evidence
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      urlPath <- "/association/find/{subject_category}/"
      if (!missing(`subject_category`)) {
        urlPath <- gsub(paste0("\\{", "subject_category", "\\}"), `subject_category`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_association_object = function(id, page, subject, object, subject_taxon, evidence, graphize, map_identifiers, fl_excludes_evidence, rows, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`subject`)) {
        queryParams['subject'] <- subject
      }

      if (!missing(`object`)) {
        queryParams['object'] <- object
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`graphize`)) {
        queryParams['graphize'] <- graphize
      }

      if (!missing(`map_identifiers`)) {
        queryParams['map_identifiers'] <- map_identifiers
      }

      if (!missing(`fl_excludes_evidence`)) {
        queryParams['fl_excludes_evidence'] <- fl_excludes_evidence
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      urlPath <- "/association/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), `id`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Association$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_association_search = function(page, subject, object, subject_taxon, evidence, graphize, map_identifiers, fl_excludes_evidence, rows, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`subject`)) {
        queryParams['subject'] <- subject
      }

      if (!missing(`object`)) {
        queryParams['object'] <- object
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`graphize`)) {
        queryParams['graphize'] <- graphize
      }

      if (!missing(`map_identifiers`)) {
        queryParams['map_identifiers'] <- map_identifiers
      }

      if (!missing(`fl_excludes_evidence`)) {
        queryParams['fl_excludes_evidence'] <- fl_excludes_evidence
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      urlPath <- "/association/find/"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_associations_between = function(subject, object, page, fl_excludes_evidence, subject_category, subject_taxon, graphize, evidence, slim, use_compact_associations, object_category, map_identifiers, rows, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`fl_excludes_evidence`)) {
        queryParams['fl_excludes_evidence'] <- fl_excludes_evidence
      }

      if (!missing(`subject_category`)) {
        queryParams['subject_category'] <- subject_category
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      if (!missing(`graphize`)) {
        queryParams['graphize'] <- graphize
      }

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`slim`)) {
        queryParams['slim'] <- slim
      }

      if (!missing(`use_compact_associations`)) {
        queryParams['use_compact_associations'] <- use_compact_associations
      }

      if (!missing(`object_category`)) {
        queryParams['object_category'] <- object_category
      }

      if (!missing(`map_identifiers`)) {
        queryParams['map_identifiers'] <- map_identifiers
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      urlPath <- "/association/between/{subject}/{object}"
      if (!missing(`subject`)) {
        urlPath <- gsub(paste0("\\{", "subject", "\\}"), `subject`, urlPath)
      }

      if (!missing(`object`)) {
        urlPath <- gsub(paste0("\\{", "object", "\\}"), `object`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_associations_from = function(subject, page, fl_excludes_evidence, subject_category, subject_taxon, graphize, evidence, slim, use_compact_associations, object_category, map_identifiers, rows, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`fl_excludes_evidence`)) {
        queryParams['fl_excludes_evidence'] <- fl_excludes_evidence
      }

      if (!missing(`subject_category`)) {
        queryParams['subject_category'] <- subject_category
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      if (!missing(`graphize`)) {
        queryParams['graphize'] <- graphize
      }

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`slim`)) {
        queryParams['slim'] <- slim
      }

      if (!missing(`use_compact_associations`)) {
        queryParams['use_compact_associations'] <- use_compact_associations
      }

      if (!missing(`object_category`)) {
        queryParams['object_category'] <- object_category
      }

      if (!missing(`map_identifiers`)) {
        queryParams['map_identifiers'] <- map_identifiers
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      urlPath <- "/association/from/{subject}"
      if (!missing(`subject`)) {
        urlPath <- gsub(paste0("\\{", "subject", "\\}"), `subject`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_associations_to = function(object, page, fl_excludes_evidence, subject_category, subject_taxon, graphize, evidence, slim, use_compact_associations, object_category, map_identifiers, rows, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`page`)) {
        queryParams['page'] <- page
      }

      if (!missing(`fl_excludes_evidence`)) {
        queryParams['fl_excludes_evidence'] <- fl_excludes_evidence
      }

      if (!missing(`subject_category`)) {
        queryParams['subject_category'] <- subject_category
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      if (!missing(`graphize`)) {
        queryParams['graphize'] <- graphize
      }

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`slim`)) {
        queryParams['slim'] <- slim
      }

      if (!missing(`use_compact_associations`)) {
        queryParams['use_compact_associations'] <- use_compact_associations
      }

      if (!missing(`object_category`)) {
        queryParams['object_category'] <- object_category
      }

      if (!missing(`map_identifiers`)) {
        queryParams['map_identifiers'] <- map_identifiers
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      urlPath <- "/association/to/{object}"
      if (!missing(`object`)) {
        urlPath <- gsub(paste0("\\{", "object", "\\}"), `object`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
