# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' BioObjectCore Class
#'
#' @field id 
#' @field label 
#' @field taxon 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BioObjectCore <- R6::R6Class(
  'BioObjectCore',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `taxon` = NULL,
    initialize = function(`id`, `label`, `taxon`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`taxon`)) {
        stopifnot(R6::is.R6(`taxon`))
        self$`taxon` <- `taxon`
      }
    },
    toJSON = function() {
      BioObjectCoreObject <- list()
      if (!is.null(self$`id`)) {
        BioObjectCoreObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        BioObjectCoreObject[['label']] <- self$`label`
      }
      if (!is.null(self$`taxon`)) {
        BioObjectCoreObject[['taxon']] <- self$`taxon`$toJSON()
      }

      BioObjectCoreObject
    },
    fromJSON = function(BioObjectCoreJson) {
      BioObjectCoreObject <- jsonlite::fromJSON(BioObjectCoreJson)
      if (!is.null(BioObjectCoreObject$`id`)) {
        self$`id` <- BioObjectCoreObject$`id`
      }
      if (!is.null(BioObjectCoreObject$`label`)) {
        self$`label` <- BioObjectCoreObject$`label`
      }
      if (!is.null(BioObjectCoreObject$`taxon`)) {
        taxonObject <- Taxon$new()
        taxonObject$fromJSON(jsonlite::toJSON(BioObjectCoreObject$taxon, auto_unbox = TRUE))
        self$`taxon` <- taxonObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "taxon": %s
        }',
        self$`id`,
        self$`label`,
        self$`taxon`$toJSON()
      )
    },
    fromJSONString = function(BioObjectCoreJson) {
      BioObjectCoreObject <- jsonlite::fromJSON(BioObjectCoreJson)
      self$`id` <- BioObjectCoreObject$`id`
      self$`label` <- BioObjectCoreObject$`label`
      TaxonObject <- Taxon$new()
      self$`taxon` <- TaxonObject$fromJSON(jsonlite::toJSON(BioObjectCoreObject$taxon, auto_unbox = TRUE))
    }
  )
)
