# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Chromosome Class
#'
#' @field id 
#' @field label 
#' @field categories 
#' @field types 
#' @field description 
#' @field consider 
#' @field deprecated 
#' @field replaced_by 
#' @field synonyms 
#' @field xrefs 
#' @field taxon 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Chromosome <- R6::R6Class(
  'Chromosome',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `categories` = NULL,
    `types` = NULL,
    `description` = NULL,
    `consider` = NULL,
    `deprecated` = NULL,
    `replaced_by` = NULL,
    `synonyms` = NULL,
    `xrefs` = NULL,
    `taxon` = NULL,
    initialize = function(`id`, `label`, `categories`, `types`, `description`, `consider`, `deprecated`, `replaced_by`, `synonyms`, `xrefs`, `taxon`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`types`)) {
        stopifnot(is.list(`types`), length(`types`) != 0)
        lapply(`types`, function(x) stopifnot(is.character(x)))
        self$`types` <- `types`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`consider`)) {
        stopifnot(is.list(`consider`), length(`consider`) != 0)
        lapply(`consider`, function(x) stopifnot(is.character(x)))
        self$`consider` <- `consider`
      }
      if (!missing(`deprecated`)) {
        self$`deprecated` <- `deprecated`
      }
      if (!missing(`replaced_by`)) {
        stopifnot(is.list(`replaced_by`), length(`replaced_by`) != 0)
        lapply(`replaced_by`, function(x) stopifnot(is.character(x)))
        self$`replaced_by` <- `replaced_by`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`xrefs`)) {
        stopifnot(is.list(`xrefs`), length(`xrefs`) != 0)
        lapply(`xrefs`, function(x) stopifnot(is.character(x)))
        self$`xrefs` <- `xrefs`
      }
      if (!missing(`taxon`)) {
        stopifnot(R6::is.R6(`taxon`))
        self$`taxon` <- `taxon`
      }
    },
    toJSON = function() {
      ChromosomeObject <- list()
      if (!is.null(self$`id`)) {
        ChromosomeObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        ChromosomeObject[['label']] <- self$`label`
      }
      if (!is.null(self$`categories`)) {
        ChromosomeObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`types`)) {
        ChromosomeObject[['types']] <- self$`types`
      }
      if (!is.null(self$`description`)) {
        ChromosomeObject[['description']] <- self$`description`
      }
      if (!is.null(self$`consider`)) {
        ChromosomeObject[['consider']] <- self$`consider`
      }
      if (!is.null(self$`deprecated`)) {
        ChromosomeObject[['deprecated']] <- self$`deprecated`
      }
      if (!is.null(self$`replaced_by`)) {
        ChromosomeObject[['replaced_by']] <- self$`replaced_by`
      }
      if (!is.null(self$`synonyms`)) {
        ChromosomeObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }
      if (!is.null(self$`xrefs`)) {
        ChromosomeObject[['xrefs']] <- self$`xrefs`
      }
      if (!is.null(self$`taxon`)) {
        ChromosomeObject[['taxon']] <- self$`taxon`$toJSON()
      }

      ChromosomeObject
    },
    fromJSON = function(ChromosomeJson) {
      ChromosomeObject <- jsonlite::fromJSON(ChromosomeJson)
      if (!is.null(ChromosomeObject$`id`)) {
        self$`id` <- ChromosomeObject$`id`
      }
      if (!is.null(ChromosomeObject$`label`)) {
        self$`label` <- ChromosomeObject$`label`
      }
      if (!is.null(ChromosomeObject$`categories`)) {
        self$`categories` <- ChromosomeObject$`categories`
      }
      if (!is.null(ChromosomeObject$`types`)) {
        self$`types` <- ChromosomeObject$`types`
      }
      if (!is.null(ChromosomeObject$`description`)) {
        self$`description` <- ChromosomeObject$`description`
      }
      if (!is.null(ChromosomeObject$`consider`)) {
        self$`consider` <- ChromosomeObject$`consider`
      }
      if (!is.null(ChromosomeObject$`deprecated`)) {
        self$`deprecated` <- ChromosomeObject$`deprecated`
      }
      if (!is.null(ChromosomeObject$`replaced_by`)) {
        self$`replaced_by` <- ChromosomeObject$`replaced_by`
      }
      if (!is.null(ChromosomeObject$`synonyms`)) {
        self$`synonyms` <- lapply(ChromosomeObject$`synonyms`, function(x) {
          synonymsObject <- SynonymPropertyValue$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
      if (!is.null(ChromosomeObject$`xrefs`)) {
        self$`xrefs` <- ChromosomeObject$`xrefs`
      }
      if (!is.null(ChromosomeObject$`taxon`)) {
        taxonObject <- Taxon$new()
        taxonObject$fromJSON(jsonlite::toJSON(ChromosomeObject$taxon, auto_unbox = TRUE))
        self$`taxon` <- taxonObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "categories": [%s],
           "types": [%s],
           "description": %s,
           "consider": [%s],
           "deprecated": %s,
           "replaced_by": [%s],
           "synonyms": [%s],
           "xrefs": [%s],
           "taxon": %s
        }',
        self$`id`,
        self$`label`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`types`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        lapply(self$`consider`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`deprecated`,
        lapply(self$`replaced_by`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`xrefs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`taxon`$toJSON()
      )
    },
    fromJSONString = function(ChromosomeJson) {
      ChromosomeObject <- jsonlite::fromJSON(ChromosomeJson)
      self$`id` <- ChromosomeObject$`id`
      self$`label` <- ChromosomeObject$`label`
      self$`categories` <- ChromosomeObject$`categories`
      self$`types` <- ChromosomeObject$`types`
      self$`description` <- ChromosomeObject$`description`
      self$`consider` <- ChromosomeObject$`consider`
      self$`deprecated` <- ChromosomeObject$`deprecated`
      self$`replaced_by` <- ChromosomeObject$`replaced_by`
      self$`synonyms` <- lapply(ChromosomeObject$`synonyms`, function(x) SynonymPropertyValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`xrefs` <- ChromosomeObject$`xrefs`
      TaxonObject <- Taxon$new()
      self$`taxon` <- TaxonObject$fromJSON(jsonlite::toJSON(ChromosomeObject$taxon, auto_unbox = TRUE))
    }
  )
)
