# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' CompactAssociationSet Class
#'
#' @field objects 
#' @field subject 
#' @field relation 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CompactAssociationSet <- R6::R6Class(
  'CompactAssociationSet',
  public = list(
    `objects` = NULL,
    `subject` = NULL,
    `relation` = NULL,
    initialize = function(`objects`, `subject`, `relation`){
      if (!missing(`objects`)) {
        stopifnot(is.list(`objects`), length(`objects`) != 0)
        lapply(`objects`, function(x) stopifnot(is.character(x)))
        self$`objects` <- `objects`
      }
      if (!missing(`subject`)) {
        stopifnot(is.character(`subject`), length(`subject`) == 1)
        self$`subject` <- `subject`
      }
      if (!missing(`relation`)) {
        stopifnot(is.character(`relation`), length(`relation`) == 1)
        self$`relation` <- `relation`
      }
    },
    toJSON = function() {
      CompactAssociationSetObject <- list()
      if (!is.null(self$`objects`)) {
        CompactAssociationSetObject[['objects']] <- self$`objects`
      }
      if (!is.null(self$`subject`)) {
        CompactAssociationSetObject[['subject']] <- self$`subject`
      }
      if (!is.null(self$`relation`)) {
        CompactAssociationSetObject[['relation']] <- self$`relation`
      }

      CompactAssociationSetObject
    },
    fromJSON = function(CompactAssociationSetJson) {
      CompactAssociationSetObject <- jsonlite::fromJSON(CompactAssociationSetJson)
      if (!is.null(CompactAssociationSetObject$`objects`)) {
        self$`objects` <- CompactAssociationSetObject$`objects`
      }
      if (!is.null(CompactAssociationSetObject$`subject`)) {
        self$`subject` <- CompactAssociationSetObject$`subject`
      }
      if (!is.null(CompactAssociationSetObject$`relation`)) {
        self$`relation` <- CompactAssociationSetObject$`relation`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "objects": [%s],
           "subject": %s,
           "relation": %s
        }',
        lapply(self$`objects`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`subject`,
        self$`relation`
      )
    },
    fromJSONString = function(CompactAssociationSetJson) {
      CompactAssociationSetObject <- jsonlite::fromJSON(CompactAssociationSetJson)
      self$`objects` <- CompactAssociationSetObject$`objects`
      self$`subject` <- CompactAssociationSetObject$`subject`
      self$`relation` <- CompactAssociationSetObject$`relation`
    }
  )
)
