# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' EntityReference Class
#'
#' @field id 
#' @field categories 
#' @field label 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntityReference <- R6::R6Class(
  'EntityReference',
  public = list(
    `id` = NULL,
    `categories` = NULL,
    `label` = NULL,
    initialize = function(`id`, `categories`, `label`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
    },
    toJSON = function() {
      EntityReferenceObject <- list()
      if (!is.null(self$`id`)) {
        EntityReferenceObject[['id']] <- self$`id`
      }
      if (!is.null(self$`categories`)) {
        EntityReferenceObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`label`)) {
        EntityReferenceObject[['label']] <- self$`label`
      }

      EntityReferenceObject
    },
    fromJSON = function(EntityReferenceJson) {
      EntityReferenceObject <- jsonlite::fromJSON(EntityReferenceJson)
      if (!is.null(EntityReferenceObject$`id`)) {
        self$`id` <- EntityReferenceObject$`id`
      }
      if (!is.null(EntityReferenceObject$`categories`)) {
        self$`categories` <- EntityReferenceObject$`categories`
      }
      if (!is.null(EntityReferenceObject$`label`)) {
        self$`label` <- EntityReferenceObject$`label`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "categories": [%s],
           "label": %s
        }',
        self$`id`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`label`
      )
    },
    fromJSONString = function(EntityReferenceJson) {
      EntityReferenceObject <- jsonlite::fromJSON(EntityReferenceJson)
      self$`id` <- EntityReferenceObject$`id`
      self$`categories` <- EntityReferenceObject$`categories`
      self$`label` <- EntityReferenceObject$`label`
    }
  )
)
