# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Genotype Class
#'
#' @field id 
#' @field label 
#' @field categories 
#' @field types 
#' @field description 
#' @field consider 
#' @field deprecated 
#' @field replaced_by 
#' @field synonyms 
#' @field xrefs 
#' @field taxon 
#' @field phenotype_associations 
#' @field gene_associations 
#' @field disease_associations 
#' @field variant_associations 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Genotype <- R6::R6Class(
  'Genotype',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `categories` = NULL,
    `types` = NULL,
    `description` = NULL,
    `consider` = NULL,
    `deprecated` = NULL,
    `replaced_by` = NULL,
    `synonyms` = NULL,
    `xrefs` = NULL,
    `taxon` = NULL,
    `phenotype_associations` = NULL,
    `gene_associations` = NULL,
    `disease_associations` = NULL,
    `variant_associations` = NULL,
    initialize = function(`id`, `label`, `categories`, `types`, `description`, `consider`, `deprecated`, `replaced_by`, `synonyms`, `xrefs`, `taxon`, `phenotype_associations`, `gene_associations`, `disease_associations`, `variant_associations`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`types`)) {
        stopifnot(is.list(`types`), length(`types`) != 0)
        lapply(`types`, function(x) stopifnot(is.character(x)))
        self$`types` <- `types`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`consider`)) {
        stopifnot(is.list(`consider`), length(`consider`) != 0)
        lapply(`consider`, function(x) stopifnot(is.character(x)))
        self$`consider` <- `consider`
      }
      if (!missing(`deprecated`)) {
        self$`deprecated` <- `deprecated`
      }
      if (!missing(`replaced_by`)) {
        stopifnot(is.list(`replaced_by`), length(`replaced_by`) != 0)
        lapply(`replaced_by`, function(x) stopifnot(is.character(x)))
        self$`replaced_by` <- `replaced_by`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`xrefs`)) {
        stopifnot(is.list(`xrefs`), length(`xrefs`) != 0)
        lapply(`xrefs`, function(x) stopifnot(is.character(x)))
        self$`xrefs` <- `xrefs`
      }
      if (!missing(`taxon`)) {
        stopifnot(R6::is.R6(`taxon`))
        self$`taxon` <- `taxon`
      }
      if (!missing(`phenotype_associations`)) {
        stopifnot(is.list(`phenotype_associations`), length(`phenotype_associations`) != 0)
        lapply(`phenotype_associations`, function(x) stopifnot(R6::is.R6(x)))
        self$`phenotype_associations` <- `phenotype_associations`
      }
      if (!missing(`gene_associations`)) {
        stopifnot(is.list(`gene_associations`), length(`gene_associations`) != 0)
        lapply(`gene_associations`, function(x) stopifnot(R6::is.R6(x)))
        self$`gene_associations` <- `gene_associations`
      }
      if (!missing(`disease_associations`)) {
        stopifnot(is.list(`disease_associations`), length(`disease_associations`) != 0)
        lapply(`disease_associations`, function(x) stopifnot(R6::is.R6(x)))
        self$`disease_associations` <- `disease_associations`
      }
      if (!missing(`variant_associations`)) {
        stopifnot(is.list(`variant_associations`), length(`variant_associations`) != 0)
        lapply(`variant_associations`, function(x) stopifnot(R6::is.R6(x)))
        self$`variant_associations` <- `variant_associations`
      }
    },
    toJSON = function() {
      GenotypeObject <- list()
      if (!is.null(self$`id`)) {
        GenotypeObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        GenotypeObject[['label']] <- self$`label`
      }
      if (!is.null(self$`categories`)) {
        GenotypeObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`types`)) {
        GenotypeObject[['types']] <- self$`types`
      }
      if (!is.null(self$`description`)) {
        GenotypeObject[['description']] <- self$`description`
      }
      if (!is.null(self$`consider`)) {
        GenotypeObject[['consider']] <- self$`consider`
      }
      if (!is.null(self$`deprecated`)) {
        GenotypeObject[['deprecated']] <- self$`deprecated`
      }
      if (!is.null(self$`replaced_by`)) {
        GenotypeObject[['replaced_by']] <- self$`replaced_by`
      }
      if (!is.null(self$`synonyms`)) {
        GenotypeObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }
      if (!is.null(self$`xrefs`)) {
        GenotypeObject[['xrefs']] <- self$`xrefs`
      }
      if (!is.null(self$`taxon`)) {
        GenotypeObject[['taxon']] <- self$`taxon`$toJSON()
      }
      if (!is.null(self$`phenotype_associations`)) {
        GenotypeObject[['phenotype_associations']] <- lapply(self$`phenotype_associations`, function(x) x$toJSON())
      }
      if (!is.null(self$`gene_associations`)) {
        GenotypeObject[['gene_associations']] <- lapply(self$`gene_associations`, function(x) x$toJSON())
      }
      if (!is.null(self$`disease_associations`)) {
        GenotypeObject[['disease_associations']] <- lapply(self$`disease_associations`, function(x) x$toJSON())
      }
      if (!is.null(self$`variant_associations`)) {
        GenotypeObject[['variant_associations']] <- lapply(self$`variant_associations`, function(x) x$toJSON())
      }

      GenotypeObject
    },
    fromJSON = function(GenotypeJson) {
      GenotypeObject <- jsonlite::fromJSON(GenotypeJson)
      if (!is.null(GenotypeObject$`id`)) {
        self$`id` <- GenotypeObject$`id`
      }
      if (!is.null(GenotypeObject$`label`)) {
        self$`label` <- GenotypeObject$`label`
      }
      if (!is.null(GenotypeObject$`categories`)) {
        self$`categories` <- GenotypeObject$`categories`
      }
      if (!is.null(GenotypeObject$`types`)) {
        self$`types` <- GenotypeObject$`types`
      }
      if (!is.null(GenotypeObject$`description`)) {
        self$`description` <- GenotypeObject$`description`
      }
      if (!is.null(GenotypeObject$`consider`)) {
        self$`consider` <- GenotypeObject$`consider`
      }
      if (!is.null(GenotypeObject$`deprecated`)) {
        self$`deprecated` <- GenotypeObject$`deprecated`
      }
      if (!is.null(GenotypeObject$`replaced_by`)) {
        self$`replaced_by` <- GenotypeObject$`replaced_by`
      }
      if (!is.null(GenotypeObject$`synonyms`)) {
        self$`synonyms` <- lapply(GenotypeObject$`synonyms`, function(x) {
          synonymsObject <- SynonymPropertyValue$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
      if (!is.null(GenotypeObject$`xrefs`)) {
        self$`xrefs` <- GenotypeObject$`xrefs`
      }
      if (!is.null(GenotypeObject$`taxon`)) {
        taxonObject <- Taxon$new()
        taxonObject$fromJSON(jsonlite::toJSON(GenotypeObject$taxon, auto_unbox = TRUE))
        self$`taxon` <- taxonObject
      }
      if (!is.null(GenotypeObject$`phenotype_associations`)) {
        self$`phenotype_associations` <- lapply(GenotypeObject$`phenotype_associations`, function(x) {
          phenotype_associationsObject <- Association$new()
          phenotype_associationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          phenotype_associationsObject
        })
      }
      if (!is.null(GenotypeObject$`gene_associations`)) {
        self$`gene_associations` <- lapply(GenotypeObject$`gene_associations`, function(x) {
          gene_associationsObject <- Association$new()
          gene_associationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          gene_associationsObject
        })
      }
      if (!is.null(GenotypeObject$`disease_associations`)) {
        self$`disease_associations` <- lapply(GenotypeObject$`disease_associations`, function(x) {
          disease_associationsObject <- Association$new()
          disease_associationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          disease_associationsObject
        })
      }
      if (!is.null(GenotypeObject$`variant_associations`)) {
        self$`variant_associations` <- lapply(GenotypeObject$`variant_associations`, function(x) {
          variant_associationsObject <- Association$new()
          variant_associationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          variant_associationsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "categories": [%s],
           "types": [%s],
           "description": %s,
           "consider": [%s],
           "deprecated": %s,
           "replaced_by": [%s],
           "synonyms": [%s],
           "xrefs": [%s],
           "taxon": %s,
           "phenotype_associations": [%s],
           "gene_associations": [%s],
           "disease_associations": [%s],
           "variant_associations": [%s]
        }',
        self$`id`,
        self$`label`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`types`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        lapply(self$`consider`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`deprecated`,
        lapply(self$`replaced_by`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`xrefs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`taxon`$toJSON(),
        lapply(self$`phenotype_associations`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`gene_associations`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`disease_associations`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`variant_associations`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GenotypeJson) {
      GenotypeObject <- jsonlite::fromJSON(GenotypeJson)
      self$`id` <- GenotypeObject$`id`
      self$`label` <- GenotypeObject$`label`
      self$`categories` <- GenotypeObject$`categories`
      self$`types` <- GenotypeObject$`types`
      self$`description` <- GenotypeObject$`description`
      self$`consider` <- GenotypeObject$`consider`
      self$`deprecated` <- GenotypeObject$`deprecated`
      self$`replaced_by` <- GenotypeObject$`replaced_by`
      self$`synonyms` <- lapply(GenotypeObject$`synonyms`, function(x) SynonymPropertyValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`xrefs` <- GenotypeObject$`xrefs`
      TaxonObject <- Taxon$new()
      self$`taxon` <- TaxonObject$fromJSON(jsonlite::toJSON(GenotypeObject$taxon, auto_unbox = TRUE))
      self$`phenotype_associations` <- lapply(GenotypeObject$`phenotype_associations`, function(x) Association$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`gene_associations` <- lapply(GenotypeObject$`gene_associations`, function(x) Association$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`disease_associations` <- lapply(GenotypeObject$`disease_associations`, function(x) Association$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`variant_associations` <- lapply(GenotypeObject$`variant_associations`, function(x) Association$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
