# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Graph Class
#'
#' @field edges 
#' @field nodes 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Graph <- R6::R6Class(
  'Graph',
  public = list(
    `edges` = NULL,
    `nodes` = NULL,
    initialize = function(`edges`, `nodes`){
      if (!missing(`edges`)) {
        stopifnot(is.list(`edges`), length(`edges`) != 0)
        lapply(`edges`, function(x) stopifnot(R6::is.R6(x)))
        self$`edges` <- `edges`
      }
      if (!missing(`nodes`)) {
        stopifnot(is.list(`nodes`), length(`nodes`) != 0)
        lapply(`nodes`, function(x) stopifnot(R6::is.R6(x)))
        self$`nodes` <- `nodes`
      }
    },
    toJSON = function() {
      GraphObject <- list()
      if (!is.null(self$`edges`)) {
        GraphObject[['edges']] <- lapply(self$`edges`, function(x) x$toJSON())
      }
      if (!is.null(self$`nodes`)) {
        GraphObject[['nodes']] <- lapply(self$`nodes`, function(x) x$toJSON())
      }

      GraphObject
    },
    fromJSON = function(GraphJson) {
      GraphObject <- jsonlite::fromJSON(GraphJson)
      if (!is.null(GraphObject$`edges`)) {
        self$`edges` <- lapply(GraphObject$`edges`, function(x) {
          edgesObject <- Edge$new()
          edgesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          edgesObject
        })
      }
      if (!is.null(GraphObject$`nodes`)) {
        self$`nodes` <- lapply(GraphObject$`nodes`, function(x) {
          nodesObject <- Node$new()
          nodesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          nodesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "edges": [%s],
           "nodes": [%s]
        }',
        lapply(self$`edges`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`nodes`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GraphJson) {
      GraphObject <- jsonlite::fromJSON(GraphJson)
      self$`edges` <- lapply(GraphObject$`edges`, function(x) Edge$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`nodes` <- lapply(GraphObject$`nodes`, function(x) Node$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
