# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' NamedObjectCore Class
#'
#' @field id 
#' @field label 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NamedObjectCore <- R6::R6Class(
  'NamedObjectCore',
  public = list(
    `id` = NULL,
    `label` = NULL,
    initialize = function(`id`, `label`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
    },
    toJSON = function() {
      NamedObjectCoreObject <- list()
      if (!is.null(self$`id`)) {
        NamedObjectCoreObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        NamedObjectCoreObject[['label']] <- self$`label`
      }

      NamedObjectCoreObject
    },
    fromJSON = function(NamedObjectCoreJson) {
      NamedObjectCoreObject <- jsonlite::fromJSON(NamedObjectCoreJson)
      if (!is.null(NamedObjectCoreObject$`id`)) {
        self$`id` <- NamedObjectCoreObject$`id`
      }
      if (!is.null(NamedObjectCoreObject$`label`)) {
        self$`label` <- NamedObjectCoreObject$`label`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s
        }',
        self$`id`,
        self$`label`
      )
    },
    fromJSONString = function(NamedObjectCoreJson) {
      NamedObjectCoreObject <- jsonlite::fromJSON(NamedObjectCoreJson)
      self$`id` <- NamedObjectCoreObject$`id`
      self$`label` <- NamedObjectCoreObject$`label`
    }
  )
)
