# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Node Class
#'
#' @field id 
#' @field lbl 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Node <- R6::R6Class(
  'Node',
  public = list(
    `id` = NULL,
    `lbl` = NULL,
    initialize = function(`id`, `lbl`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`lbl`)) {
        stopifnot(is.character(`lbl`), length(`lbl`) == 1)
        self$`lbl` <- `lbl`
      }
    },
    toJSON = function() {
      NodeObject <- list()
      if (!is.null(self$`id`)) {
        NodeObject[['id']] <- self$`id`
      }
      if (!is.null(self$`lbl`)) {
        NodeObject[['lbl']] <- self$`lbl`
      }

      NodeObject
    },
    fromJSON = function(NodeJson) {
      NodeObject <- jsonlite::fromJSON(NodeJson)
      if (!is.null(NodeObject$`id`)) {
        self$`id` <- NodeObject$`id`
      }
      if (!is.null(NodeObject$`lbl`)) {
        self$`lbl` <- NodeObject$`lbl`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "lbl": %s
        }',
        self$`id`,
        self$`lbl`
      )
    },
    fromJSONString = function(NodeJson) {
      NodeObject <- jsonlite::fromJSON(NodeJson)
      self$`id` <- NodeObject$`id`
      self$`lbl` <- NodeObject$`lbl`
    }
  )
)
