# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Ontol operations
#' @description swagger.Ontol
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' get_extract_ontology_subgraph_resource Extract a subgraph from an ontology
#'
#'
#' get_information_content_resource Returns information content (IC) for a set of relevant ontology classes
#'
#'
#' get_test_me TEST
#'
#' }
#'
#' @export
OntolApi <- R6::R6Class(
  'OntolApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    get_extract_ontology_subgraph_resource = function(node, ontology, cnode, relation, include_meta, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`cnode`)) {
        queryParams['cnode'] <- cnode
      }

      if (!missing(`relation`)) {
        queryParams['relation'] <- relation
      }

      if (!missing(`include_meta`)) {
        queryParams['include_meta'] <- include_meta
      }

      urlPath <- "/ontol/subgraph/{ontology}/{node}"
      if (!missing(`node`)) {
        urlPath <- gsub(paste0("\\{", "node", "\\}"), `node`, urlPath)
      }

      if (!missing(`ontology`)) {
        urlPath <- gsub(paste0("\\{", "ontology", "\\}"), `ontology`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_information_content_resource = function(subject_category, object_category, subject_taxon, evidence, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      urlPath <- "/ontol/information_content/{subject_category}/{object_category}/{subject_taxon}"
      if (!missing(`subject_category`)) {
        urlPath <- gsub(paste0("\\{", "subject_category", "\\}"), `subject_category`, urlPath)
      }

      if (!missing(`object_category`)) {
        urlPath <- gsub(paste0("\\{", "object_category", "\\}"), `object_category`, urlPath)
      }

      if (!missing(`subject_taxon`)) {
        urlPath <- gsub(paste0("\\{", "subject_taxon", "\\}"), `subject_taxon`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_test_me = function(ontology, cnode, relation, include_meta, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`cnode`)) {
        queryParams['cnode'] <- cnode
      }

      if (!missing(`relation`)) {
        queryParams['relation'] <- relation
      }

      if (!missing(`include_meta`)) {
        queryParams['include_meta'] <- include_meta
      }

      urlPath <- "/ontol/testme/{ontology}"
      if (!missing(`ontology`)) {
        urlPath <- gsub(paste0("\\{", "ontology", "\\}"), `ontology`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
