# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PageOfVariantSets Class
#'
#' @field total 
#' @field page 
#' @field pages 
#' @field per_page 
#' @field items 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PageOfVariantSets <- R6::R6Class(
  'PageOfVariantSets',
  public = list(
    `total` = NULL,
    `page` = NULL,
    `pages` = NULL,
    `per_page` = NULL,
    `items` = NULL,
    initialize = function(`total`, `page`, `pages`, `per_page`, `items`){
      if (!missing(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!missing(`page`)) {
        stopifnot(is.numeric(`page`), length(`page`) == 1)
        self$`page` <- `page`
      }
      if (!missing(`pages`)) {
        stopifnot(is.numeric(`pages`), length(`pages`) == 1)
        self$`pages` <- `pages`
      }
      if (!missing(`per_page`)) {
        stopifnot(is.numeric(`per_page`), length(`per_page`) == 1)
        self$`per_page` <- `per_page`
      }
      if (!missing(`items`)) {
        stopifnot(is.list(`items`), length(`items`) != 0)
        lapply(`items`, function(x) stopifnot(R6::is.R6(x)))
        self$`items` <- `items`
      }
    },
    toJSON = function() {
      PageOfVariantSetsObject <- list()
      if (!is.null(self$`total`)) {
        PageOfVariantSetsObject[['total']] <- self$`total`
      }
      if (!is.null(self$`page`)) {
        PageOfVariantSetsObject[['page']] <- self$`page`
      }
      if (!is.null(self$`pages`)) {
        PageOfVariantSetsObject[['pages']] <- self$`pages`
      }
      if (!is.null(self$`per_page`)) {
        PageOfVariantSetsObject[['per_page']] <- self$`per_page`
      }
      if (!is.null(self$`items`)) {
        PageOfVariantSetsObject[['items']] <- lapply(self$`items`, function(x) x$toJSON())
      }

      PageOfVariantSetsObject
    },
    fromJSON = function(PageOfVariantSetsJson) {
      PageOfVariantSetsObject <- jsonlite::fromJSON(PageOfVariantSetsJson)
      if (!is.null(PageOfVariantSetsObject$`total`)) {
        self$`total` <- PageOfVariantSetsObject$`total`
      }
      if (!is.null(PageOfVariantSetsObject$`page`)) {
        self$`page` <- PageOfVariantSetsObject$`page`
      }
      if (!is.null(PageOfVariantSetsObject$`pages`)) {
        self$`pages` <- PageOfVariantSetsObject$`pages`
      }
      if (!is.null(PageOfVariantSetsObject$`per_page`)) {
        self$`per_page` <- PageOfVariantSetsObject$`per_page`
      }
      if (!is.null(PageOfVariantSetsObject$`items`)) {
        self$`items` <- lapply(PageOfVariantSetsObject$`items`, function(x) {
          itemsObject <- VariantSet$new()
          itemsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          itemsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "total": %d,
           "page": %d,
           "pages": %d,
           "per_page": %d,
           "items": [%s]
        }',
        self$`total`,
        self$`page`,
        self$`pages`,
        self$`per_page`,
        lapply(self$`items`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(PageOfVariantSetsJson) {
      PageOfVariantSetsObject <- jsonlite::fromJSON(PageOfVariantSetsJson)
      self$`total` <- PageOfVariantSetsObject$`total`
      self$`page` <- PageOfVariantSetsObject$`page`
      self$`pages` <- PageOfVariantSetsObject$`pages`
      self$`per_page` <- PageOfVariantSetsObject$`per_page`
      self$`items` <- lapply(PageOfVariantSetsObject$`items`, function(x) VariantSet$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
