# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Pairsim operations
#' @description swagger.Pairsim
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' get_pair_sim_jaccard_resource Get pairwise similarity
#'
#' }
#'
#' @export
PairsimApi <- R6::R6Class(
  'PairsimApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    get_pair_sim_jaccard_resource = function(id1, id2, object_category, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`object_category`)) {
        queryParams['object_category'] <- object_category
      }

      urlPath <- "/pair/sim/jaccard/{id1}/{id2}/"
      if (!missing(`id1`)) {
        urlPath <- gsub(paste0("\\{", "id1", "\\}"), `id1`, urlPath)
      }

      if (!missing(`id2`)) {
        urlPath <- gsub(paste0("\\{", "id2", "\\}"), `id2`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
