# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Relationusage operations
#' @description swagger.Relationusage
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' get_relation_usage_between_resource All relations used plus count of associations
#'
#'
#' get_relation_usage_pivot_label_resource Relation usage count for all subj x obj category combinations, showing label
#'
#'
#' get_relation_usage_pivot_resource Relation usage count for all subj x obj category combinations
#'
#'
#' get_relation_usage_resource All relations used plus count of associations
#'
#' }
#'
#' @export
RelationusageApi <- R6::R6Class(
  'RelationusageApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    get_relation_usage_between_resource = function(subject_category, object_category, evidence, subject_taxon, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      urlPath <- "/relation/usage/between/{subject_category}/{object_category}"
      if (!missing(`subject_category`)) {
        urlPath <- gsub(paste0("\\{", "subject_category", "\\}"), `subject_category`, urlPath)
      }

      if (!missing(`object_category`)) {
        urlPath <- gsub(paste0("\\{", "object_category", "\\}"), `object_category`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_relation_usage_pivot_label_resource = function(evidence, subject_taxon, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      urlPath <- "/relation/usage/pivot/label"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_relation_usage_pivot_resource = function(evidence, subject_taxon, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      urlPath <- "/relation/usage/pivot/"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_relation_usage_resource = function(evidence, subject_taxon, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`evidence`)) {
        queryParams['evidence'] <- evidence
      }

      if (!missing(`subject_taxon`)) {
        queryParams['subject_taxon'] <- subject_taxon
      }

      urlPath <- "/relation/usage/"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- AssociationResults$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
