# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Relation Class
#'
#' @field id 
#' @field label 
#' @field categories 
#' @field types 
#' @field description 
#' @field consider 
#' @field deprecated 
#' @field replaced_by 
#' @field synonyms 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Relation <- R6::R6Class(
  'Relation',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `categories` = NULL,
    `types` = NULL,
    `description` = NULL,
    `consider` = NULL,
    `deprecated` = NULL,
    `replaced_by` = NULL,
    `synonyms` = NULL,
    initialize = function(`id`, `label`, `categories`, `types`, `description`, `consider`, `deprecated`, `replaced_by`, `synonyms`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`types`)) {
        stopifnot(is.list(`types`), length(`types`) != 0)
        lapply(`types`, function(x) stopifnot(is.character(x)))
        self$`types` <- `types`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`consider`)) {
        stopifnot(is.list(`consider`), length(`consider`) != 0)
        lapply(`consider`, function(x) stopifnot(is.character(x)))
        self$`consider` <- `consider`
      }
      if (!missing(`deprecated`)) {
        self$`deprecated` <- `deprecated`
      }
      if (!missing(`replaced_by`)) {
        stopifnot(is.list(`replaced_by`), length(`replaced_by`) != 0)
        lapply(`replaced_by`, function(x) stopifnot(is.character(x)))
        self$`replaced_by` <- `replaced_by`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
    },
    toJSON = function() {
      RelationObject <- list()
      if (!is.null(self$`id`)) {
        RelationObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        RelationObject[['label']] <- self$`label`
      }
      if (!is.null(self$`categories`)) {
        RelationObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`types`)) {
        RelationObject[['types']] <- self$`types`
      }
      if (!is.null(self$`description`)) {
        RelationObject[['description']] <- self$`description`
      }
      if (!is.null(self$`consider`)) {
        RelationObject[['consider']] <- self$`consider`
      }
      if (!is.null(self$`deprecated`)) {
        RelationObject[['deprecated']] <- self$`deprecated`
      }
      if (!is.null(self$`replaced_by`)) {
        RelationObject[['replaced_by']] <- self$`replaced_by`
      }
      if (!is.null(self$`synonyms`)) {
        RelationObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }

      RelationObject
    },
    fromJSON = function(RelationJson) {
      RelationObject <- jsonlite::fromJSON(RelationJson)
      if (!is.null(RelationObject$`id`)) {
        self$`id` <- RelationObject$`id`
      }
      if (!is.null(RelationObject$`label`)) {
        self$`label` <- RelationObject$`label`
      }
      if (!is.null(RelationObject$`categories`)) {
        self$`categories` <- RelationObject$`categories`
      }
      if (!is.null(RelationObject$`types`)) {
        self$`types` <- RelationObject$`types`
      }
      if (!is.null(RelationObject$`description`)) {
        self$`description` <- RelationObject$`description`
      }
      if (!is.null(RelationObject$`consider`)) {
        self$`consider` <- RelationObject$`consider`
      }
      if (!is.null(RelationObject$`deprecated`)) {
        self$`deprecated` <- RelationObject$`deprecated`
      }
      if (!is.null(RelationObject$`replaced_by`)) {
        self$`replaced_by` <- RelationObject$`replaced_by`
      }
      if (!is.null(RelationObject$`synonyms`)) {
        self$`synonyms` <- lapply(RelationObject$`synonyms`, function(x) {
          synonymsObject <- SynonymPropertyValue$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "categories": [%s],
           "types": [%s],
           "description": %s,
           "consider": [%s],
           "deprecated": %s,
           "replaced_by": [%s],
           "synonyms": [%s]
        }',
        self$`id`,
        self$`label`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`types`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        lapply(self$`consider`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`deprecated`,
        lapply(self$`replaced_by`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(RelationJson) {
      RelationObject <- jsonlite::fromJSON(RelationJson)
      self$`id` <- RelationObject$`id`
      self$`label` <- RelationObject$`label`
      self$`categories` <- RelationObject$`categories`
      self$`types` <- RelationObject$`types`
      self$`description` <- RelationObject$`description`
      self$`consider` <- RelationObject$`consider`
      self$`deprecated` <- RelationObject$`deprecated`
      self$`replaced_by` <- RelationObject$`replaced_by`
      self$`synonyms` <- lapply(RelationObject$`synonyms`, function(x) SynonymPropertyValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
