# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SearchResult Class
#'
#' @field start 
#' @field facet_pivot 
#' @field facet_counts 
#' @field numFound 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SearchResult <- R6::R6Class(
  'SearchResult',
  public = list(
    `start` = NULL,
    `facet_pivot` = NULL,
    `facet_counts` = NULL,
    `numFound` = NULL,
    initialize = function(`start`, `facet_pivot`, `facet_counts`, `numFound`){
      if (!missing(`start`)) {
        stopifnot(is.numeric(`start`), length(`start`) == 1)
        self$`start` <- `start`
      }
      if (!missing(`facet_pivot`)) {
        stopifnot(R6::is.R6(`facet_pivot`))
        self$`facet_pivot` <- `facet_pivot`
      }
      if (!missing(`facet_counts`)) {
        stopifnot(R6::is.R6(`facet_counts`))
        self$`facet_counts` <- `facet_counts`
      }
      if (!missing(`numFound`)) {
        stopifnot(is.numeric(`numFound`), length(`numFound`) == 1)
        self$`numFound` <- `numFound`
      }
    },
    toJSON = function() {
      SearchResultObject <- list()
      if (!is.null(self$`start`)) {
        SearchResultObject[['start']] <- self$`start`
      }
      if (!is.null(self$`facet_pivot`)) {
        SearchResultObject[['facet_pivot']] <- self$`facet_pivot`$toJSON()
      }
      if (!is.null(self$`facet_counts`)) {
        SearchResultObject[['facet_counts']] <- self$`facet_counts`$toJSON()
      }
      if (!is.null(self$`numFound`)) {
        SearchResultObject[['numFound']] <- self$`numFound`
      }

      SearchResultObject
    },
    fromJSON = function(SearchResultJson) {
      SearchResultObject <- jsonlite::fromJSON(SearchResultJson)
      if (!is.null(SearchResultObject$`start`)) {
        self$`start` <- SearchResultObject$`start`
      }
      if (!is.null(SearchResultObject$`facet_pivot`)) {
        facet_pivotObject <- TODO_OBJECT_MAPPING$new()
        facet_pivotObject$fromJSON(jsonlite::toJSON(SearchResultObject$facet_pivot, auto_unbox = TRUE))
        self$`facet_pivot` <- facet_pivotObject
      }
      if (!is.null(SearchResultObject$`facet_counts`)) {
        facet_countsObject <- TODO_OBJECT_MAPPING$new()
        facet_countsObject$fromJSON(jsonlite::toJSON(SearchResultObject$facet_counts, auto_unbox = TRUE))
        self$`facet_counts` <- facet_countsObject
      }
      if (!is.null(SearchResultObject$`numFound`)) {
        self$`numFound` <- SearchResultObject$`numFound`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "start": %d,
           "facet_pivot": %s,
           "facet_counts": %s,
           "numFound": %d
        }',
        self$`start`,
        self$`facet_pivot`$toJSON(),
        self$`facet_counts`$toJSON(),
        self$`numFound`
      )
    },
    fromJSONString = function(SearchResultJson) {
      SearchResultObject <- jsonlite::fromJSON(SearchResultJson)
      self$`start` <- SearchResultObject$`start`
      TODO_OBJECT_MAPPINGObject <- TODO_OBJECT_MAPPING$new()
      self$`facet_pivot` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(SearchResultObject$facet_pivot, auto_unbox = TRUE))
      TODO_OBJECT_MAPPINGObject <- TODO_OBJECT_MAPPING$new()
      self$`facet_counts` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(SearchResultObject$facet_counts, auto_unbox = TRUE))
      self$`numFound` <- SearchResultObject$`numFound`
    }
  )
)
