# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title Search operations
#' @description swagger.Search
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' get_autocomplete Returns list of matching concepts or entities using lexical search
#'
#'
#' get_search_entities Returns list of matching concepts or entities using lexical search
#'
#' }
#'
#' @export
SearchApi <- R6::R6Class(
  'SearchApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    get_autocomplete = function(term, start, rows, category, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`start`)) {
        queryParams['start'] <- start
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      if (!missing(`category`)) {
        queryParams['category'] <- category
      }

      urlPath <- "/search/entity/autocomplete/{term}"
      if (!missing(`term`)) {
        urlPath <- gsub(paste0("\\{", "term", "\\}"), `term`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_search_entities = function(term, start, rows, category, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`start`)) {
        queryParams['start'] <- start
      }

      if (!missing(`rows`)) {
        queryParams['rows'] <- rows
      }

      if (!missing(`category`)) {
        queryParams['category'] <- category
      }

      urlPath <- "/search/entity/{term}"
      if (!missing(`term`)) {
        urlPath <- gsub(paste0("\\{", "term", "\\}"), `term`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        # void response, no need to return anything
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
