# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Seq Class
#'
#' @field id 
#' @field label 
#' @field categories 
#' @field types 
#' @field description 
#' @field consider 
#' @field deprecated 
#' @field replaced_by 
#' @field synonyms 
#' @field xrefs 
#' @field taxon 
#' @field md5checksum 
#' @field residues 
#' @field alphabet 
#' @field seqlen 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Seq <- R6::R6Class(
  'Seq',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `categories` = NULL,
    `types` = NULL,
    `description` = NULL,
    `consider` = NULL,
    `deprecated` = NULL,
    `replaced_by` = NULL,
    `synonyms` = NULL,
    `xrefs` = NULL,
    `taxon` = NULL,
    `md5checksum` = NULL,
    `residues` = NULL,
    `alphabet` = NULL,
    `seqlen` = NULL,
    initialize = function(`id`, `label`, `categories`, `types`, `description`, `consider`, `deprecated`, `replaced_by`, `synonyms`, `xrefs`, `taxon`, `md5checksum`, `residues`, `alphabet`, `seqlen`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`types`)) {
        stopifnot(is.list(`types`), length(`types`) != 0)
        lapply(`types`, function(x) stopifnot(is.character(x)))
        self$`types` <- `types`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`consider`)) {
        stopifnot(is.list(`consider`), length(`consider`) != 0)
        lapply(`consider`, function(x) stopifnot(is.character(x)))
        self$`consider` <- `consider`
      }
      if (!missing(`deprecated`)) {
        self$`deprecated` <- `deprecated`
      }
      if (!missing(`replaced_by`)) {
        stopifnot(is.list(`replaced_by`), length(`replaced_by`) != 0)
        lapply(`replaced_by`, function(x) stopifnot(is.character(x)))
        self$`replaced_by` <- `replaced_by`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`xrefs`)) {
        stopifnot(is.list(`xrefs`), length(`xrefs`) != 0)
        lapply(`xrefs`, function(x) stopifnot(is.character(x)))
        self$`xrefs` <- `xrefs`
      }
      if (!missing(`taxon`)) {
        stopifnot(R6::is.R6(`taxon`))
        self$`taxon` <- `taxon`
      }
      if (!missing(`md5checksum`)) {
        stopifnot(is.character(`md5checksum`), length(`md5checksum`) == 1)
        self$`md5checksum` <- `md5checksum`
      }
      if (!missing(`residues`)) {
        stopifnot(is.character(`residues`), length(`residues`) == 1)
        self$`residues` <- `residues`
      }
      if (!missing(`alphabet`)) {
        stopifnot(is.character(`alphabet`), length(`alphabet`) == 1)
        self$`alphabet` <- `alphabet`
      }
      if (!missing(`seqlen`)) {
        stopifnot(is.character(`seqlen`), length(`seqlen`) == 1)
        self$`seqlen` <- `seqlen`
      }
    },
    toJSON = function() {
      SeqObject <- list()
      if (!is.null(self$`id`)) {
        SeqObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        SeqObject[['label']] <- self$`label`
      }
      if (!is.null(self$`categories`)) {
        SeqObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`types`)) {
        SeqObject[['types']] <- self$`types`
      }
      if (!is.null(self$`description`)) {
        SeqObject[['description']] <- self$`description`
      }
      if (!is.null(self$`consider`)) {
        SeqObject[['consider']] <- self$`consider`
      }
      if (!is.null(self$`deprecated`)) {
        SeqObject[['deprecated']] <- self$`deprecated`
      }
      if (!is.null(self$`replaced_by`)) {
        SeqObject[['replaced_by']] <- self$`replaced_by`
      }
      if (!is.null(self$`synonyms`)) {
        SeqObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }
      if (!is.null(self$`xrefs`)) {
        SeqObject[['xrefs']] <- self$`xrefs`
      }
      if (!is.null(self$`taxon`)) {
        SeqObject[['taxon']] <- self$`taxon`$toJSON()
      }
      if (!is.null(self$`md5checksum`)) {
        SeqObject[['md5checksum']] <- self$`md5checksum`
      }
      if (!is.null(self$`residues`)) {
        SeqObject[['residues']] <- self$`residues`
      }
      if (!is.null(self$`alphabet`)) {
        SeqObject[['alphabet']] <- self$`alphabet`
      }
      if (!is.null(self$`seqlen`)) {
        SeqObject[['seqlen']] <- self$`seqlen`
      }

      SeqObject
    },
    fromJSON = function(SeqJson) {
      SeqObject <- jsonlite::fromJSON(SeqJson)
      if (!is.null(SeqObject$`id`)) {
        self$`id` <- SeqObject$`id`
      }
      if (!is.null(SeqObject$`label`)) {
        self$`label` <- SeqObject$`label`
      }
      if (!is.null(SeqObject$`categories`)) {
        self$`categories` <- SeqObject$`categories`
      }
      if (!is.null(SeqObject$`types`)) {
        self$`types` <- SeqObject$`types`
      }
      if (!is.null(SeqObject$`description`)) {
        self$`description` <- SeqObject$`description`
      }
      if (!is.null(SeqObject$`consider`)) {
        self$`consider` <- SeqObject$`consider`
      }
      if (!is.null(SeqObject$`deprecated`)) {
        self$`deprecated` <- SeqObject$`deprecated`
      }
      if (!is.null(SeqObject$`replaced_by`)) {
        self$`replaced_by` <- SeqObject$`replaced_by`
      }
      if (!is.null(SeqObject$`synonyms`)) {
        self$`synonyms` <- lapply(SeqObject$`synonyms`, function(x) {
          synonymsObject <- SynonymPropertyValue$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
      if (!is.null(SeqObject$`xrefs`)) {
        self$`xrefs` <- SeqObject$`xrefs`
      }
      if (!is.null(SeqObject$`taxon`)) {
        taxonObject <- Taxon$new()
        taxonObject$fromJSON(jsonlite::toJSON(SeqObject$taxon, auto_unbox = TRUE))
        self$`taxon` <- taxonObject
      }
      if (!is.null(SeqObject$`md5checksum`)) {
        self$`md5checksum` <- SeqObject$`md5checksum`
      }
      if (!is.null(SeqObject$`residues`)) {
        self$`residues` <- SeqObject$`residues`
      }
      if (!is.null(SeqObject$`alphabet`)) {
        self$`alphabet` <- SeqObject$`alphabet`
      }
      if (!is.null(SeqObject$`seqlen`)) {
        self$`seqlen` <- SeqObject$`seqlen`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "categories": [%s],
           "types": [%s],
           "description": %s,
           "consider": [%s],
           "deprecated": %s,
           "replaced_by": [%s],
           "synonyms": [%s],
           "xrefs": [%s],
           "taxon": %s,
           "md5checksum": %s,
           "residues": %s,
           "alphabet": %s,
           "seqlen": %s
        }',
        self$`id`,
        self$`label`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`types`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        lapply(self$`consider`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`deprecated`,
        lapply(self$`replaced_by`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`xrefs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`taxon`$toJSON(),
        self$`md5checksum`,
        self$`residues`,
        self$`alphabet`,
        self$`seqlen`
      )
    },
    fromJSONString = function(SeqJson) {
      SeqObject <- jsonlite::fromJSON(SeqJson)
      self$`id` <- SeqObject$`id`
      self$`label` <- SeqObject$`label`
      self$`categories` <- SeqObject$`categories`
      self$`types` <- SeqObject$`types`
      self$`description` <- SeqObject$`description`
      self$`consider` <- SeqObject$`consider`
      self$`deprecated` <- SeqObject$`deprecated`
      self$`replaced_by` <- SeqObject$`replaced_by`
      self$`synonyms` <- lapply(SeqObject$`synonyms`, function(x) SynonymPropertyValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`xrefs` <- SeqObject$`xrefs`
      TaxonObject <- Taxon$new()
      self$`taxon` <- TaxonObject$fromJSON(jsonlite::toJSON(SeqObject$taxon, auto_unbox = TRUE))
      self$`md5checksum` <- SeqObject$`md5checksum`
      self$`residues` <- SeqObject$`residues`
      self$`alphabet` <- SeqObject$`alphabet`
      self$`seqlen` <- SeqObject$`seqlen`
    }
  )
)
