# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SequenceLocation Class
#'
#' @field id 
#' @field label 
#' @field categories 
#' @field types 
#' @field description 
#' @field consider 
#' @field deprecated 
#' @field replaced_by 
#' @field synonyms 
#' @field xrefs 
#' @field taxon 
#' @field start 
#' @field strand 
#' @field phase 
#' @field end 
#' @field score 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SequenceLocation <- R6::R6Class(
  'SequenceLocation',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `categories` = NULL,
    `types` = NULL,
    `description` = NULL,
    `consider` = NULL,
    `deprecated` = NULL,
    `replaced_by` = NULL,
    `synonyms` = NULL,
    `xrefs` = NULL,
    `taxon` = NULL,
    `start` = NULL,
    `strand` = NULL,
    `phase` = NULL,
    `end` = NULL,
    `score` = NULL,
    initialize = function(`id`, `label`, `categories`, `types`, `description`, `consider`, `deprecated`, `replaced_by`, `synonyms`, `xrefs`, `taxon`, `start`, `strand`, `phase`, `end`, `score`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`types`)) {
        stopifnot(is.list(`types`), length(`types`) != 0)
        lapply(`types`, function(x) stopifnot(is.character(x)))
        self$`types` <- `types`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`consider`)) {
        stopifnot(is.list(`consider`), length(`consider`) != 0)
        lapply(`consider`, function(x) stopifnot(is.character(x)))
        self$`consider` <- `consider`
      }
      if (!missing(`deprecated`)) {
        self$`deprecated` <- `deprecated`
      }
      if (!missing(`replaced_by`)) {
        stopifnot(is.list(`replaced_by`), length(`replaced_by`) != 0)
        lapply(`replaced_by`, function(x) stopifnot(is.character(x)))
        self$`replaced_by` <- `replaced_by`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`xrefs`)) {
        stopifnot(is.list(`xrefs`), length(`xrefs`) != 0)
        lapply(`xrefs`, function(x) stopifnot(is.character(x)))
        self$`xrefs` <- `xrefs`
      }
      if (!missing(`taxon`)) {
        stopifnot(R6::is.R6(`taxon`))
        self$`taxon` <- `taxon`
      }
      if (!missing(`start`)) {
        stopifnot(R6::is.R6(`start`))
        self$`start` <- `start`
      }
      if (!missing(`strand`)) {
        stopifnot(is.numeric(`strand`), length(`strand`) == 1)
        self$`strand` <- `strand`
      }
      if (!missing(`phase`)) {
        stopifnot(is.numeric(`phase`), length(`phase`) == 1)
        self$`phase` <- `phase`
      }
      if (!missing(`end`)) {
        stopifnot(R6::is.R6(`end`))
        self$`end` <- `end`
      }
      if (!missing(`score`)) {
        stopifnot(is.numeric(`score`), length(`score`) == 1)
        self$`score` <- `score`
      }
    },
    toJSON = function() {
      SequenceLocationObject <- list()
      if (!is.null(self$`id`)) {
        SequenceLocationObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        SequenceLocationObject[['label']] <- self$`label`
      }
      if (!is.null(self$`categories`)) {
        SequenceLocationObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`types`)) {
        SequenceLocationObject[['types']] <- self$`types`
      }
      if (!is.null(self$`description`)) {
        SequenceLocationObject[['description']] <- self$`description`
      }
      if (!is.null(self$`consider`)) {
        SequenceLocationObject[['consider']] <- self$`consider`
      }
      if (!is.null(self$`deprecated`)) {
        SequenceLocationObject[['deprecated']] <- self$`deprecated`
      }
      if (!is.null(self$`replaced_by`)) {
        SequenceLocationObject[['replaced_by']] <- self$`replaced_by`
      }
      if (!is.null(self$`synonyms`)) {
        SequenceLocationObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }
      if (!is.null(self$`xrefs`)) {
        SequenceLocationObject[['xrefs']] <- self$`xrefs`
      }
      if (!is.null(self$`taxon`)) {
        SequenceLocationObject[['taxon']] <- self$`taxon`$toJSON()
      }
      if (!is.null(self$`start`)) {
        SequenceLocationObject[['start']] <- self$`start`$toJSON()
      }
      if (!is.null(self$`strand`)) {
        SequenceLocationObject[['strand']] <- self$`strand`
      }
      if (!is.null(self$`phase`)) {
        SequenceLocationObject[['phase']] <- self$`phase`
      }
      if (!is.null(self$`end`)) {
        SequenceLocationObject[['end']] <- self$`end`$toJSON()
      }
      if (!is.null(self$`score`)) {
        SequenceLocationObject[['score']] <- self$`score`
      }

      SequenceLocationObject
    },
    fromJSON = function(SequenceLocationJson) {
      SequenceLocationObject <- jsonlite::fromJSON(SequenceLocationJson)
      if (!is.null(SequenceLocationObject$`id`)) {
        self$`id` <- SequenceLocationObject$`id`
      }
      if (!is.null(SequenceLocationObject$`label`)) {
        self$`label` <- SequenceLocationObject$`label`
      }
      if (!is.null(SequenceLocationObject$`categories`)) {
        self$`categories` <- SequenceLocationObject$`categories`
      }
      if (!is.null(SequenceLocationObject$`types`)) {
        self$`types` <- SequenceLocationObject$`types`
      }
      if (!is.null(SequenceLocationObject$`description`)) {
        self$`description` <- SequenceLocationObject$`description`
      }
      if (!is.null(SequenceLocationObject$`consider`)) {
        self$`consider` <- SequenceLocationObject$`consider`
      }
      if (!is.null(SequenceLocationObject$`deprecated`)) {
        self$`deprecated` <- SequenceLocationObject$`deprecated`
      }
      if (!is.null(SequenceLocationObject$`replaced_by`)) {
        self$`replaced_by` <- SequenceLocationObject$`replaced_by`
      }
      if (!is.null(SequenceLocationObject$`synonyms`)) {
        self$`synonyms` <- lapply(SequenceLocationObject$`synonyms`, function(x) {
          synonymsObject <- SynonymPropertyValue$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
      if (!is.null(SequenceLocationObject$`xrefs`)) {
        self$`xrefs` <- SequenceLocationObject$`xrefs`
      }
      if (!is.null(SequenceLocationObject$`taxon`)) {
        taxonObject <- Taxon$new()
        taxonObject$fromJSON(jsonlite::toJSON(SequenceLocationObject$taxon, auto_unbox = TRUE))
        self$`taxon` <- taxonObject
      }
      if (!is.null(SequenceLocationObject$`start`)) {
        startObject <- SequencePosition$new()
        startObject$fromJSON(jsonlite::toJSON(SequenceLocationObject$start, auto_unbox = TRUE))
        self$`start` <- startObject
      }
      if (!is.null(SequenceLocationObject$`strand`)) {
        self$`strand` <- SequenceLocationObject$`strand`
      }
      if (!is.null(SequenceLocationObject$`phase`)) {
        self$`phase` <- SequenceLocationObject$`phase`
      }
      if (!is.null(SequenceLocationObject$`end`)) {
        endObject <- SequencePosition$new()
        endObject$fromJSON(jsonlite::toJSON(SequenceLocationObject$end, auto_unbox = TRUE))
        self$`end` <- endObject
      }
      if (!is.null(SequenceLocationObject$`score`)) {
        self$`score` <- SequenceLocationObject$`score`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "categories": [%s],
           "types": [%s],
           "description": %s,
           "consider": [%s],
           "deprecated": %s,
           "replaced_by": [%s],
           "synonyms": [%s],
           "xrefs": [%s],
           "taxon": %s,
           "start": %s,
           "strand": %d,
           "phase": %d,
           "end": %s,
           "score": %d
        }',
        self$`id`,
        self$`label`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`types`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        lapply(self$`consider`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`deprecated`,
        lapply(self$`replaced_by`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`xrefs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`taxon`$toJSON(),
        self$`start`$toJSON(),
        self$`strand`,
        self$`phase`,
        self$`end`$toJSON(),
        self$`score`
      )
    },
    fromJSONString = function(SequenceLocationJson) {
      SequenceLocationObject <- jsonlite::fromJSON(SequenceLocationJson)
      self$`id` <- SequenceLocationObject$`id`
      self$`label` <- SequenceLocationObject$`label`
      self$`categories` <- SequenceLocationObject$`categories`
      self$`types` <- SequenceLocationObject$`types`
      self$`description` <- SequenceLocationObject$`description`
      self$`consider` <- SequenceLocationObject$`consider`
      self$`deprecated` <- SequenceLocationObject$`deprecated`
      self$`replaced_by` <- SequenceLocationObject$`replaced_by`
      self$`synonyms` <- lapply(SequenceLocationObject$`synonyms`, function(x) SynonymPropertyValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`xrefs` <- SequenceLocationObject$`xrefs`
      TaxonObject <- Taxon$new()
      self$`taxon` <- TaxonObject$fromJSON(jsonlite::toJSON(SequenceLocationObject$taxon, auto_unbox = TRUE))
      SequencePositionObject <- SequencePosition$new()
      self$`start` <- SequencePositionObject$fromJSON(jsonlite::toJSON(SequenceLocationObject$start, auto_unbox = TRUE))
      self$`strand` <- SequenceLocationObject$`strand`
      self$`phase` <- SequenceLocationObject$`phase`
      SequencePositionObject <- SequencePosition$new()
      self$`end` <- SequencePositionObject$fromJSON(jsonlite::toJSON(SequenceLocationObject$end, auto_unbox = TRUE))
      self$`score` <- SequenceLocationObject$`score`
    }
  )
)
