# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SequencePosition Class
#'
#' @field reference 
#' @field position 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SequencePosition <- R6::R6Class(
  'SequencePosition',
  public = list(
    `reference` = NULL,
    `position` = NULL,
    initialize = function(`reference`, `position`){
      if (!missing(`reference`)) {
        stopifnot(is.character(`reference`), length(`reference`) == 1)
        self$`reference` <- `reference`
      }
      if (!missing(`position`)) {
        stopifnot(is.numeric(`position`), length(`position`) == 1)
        self$`position` <- `position`
      }
    },
    toJSON = function() {
      SequencePositionObject <- list()
      if (!is.null(self$`reference`)) {
        SequencePositionObject[['reference']] <- self$`reference`
      }
      if (!is.null(self$`position`)) {
        SequencePositionObject[['position']] <- self$`position`
      }

      SequencePositionObject
    },
    fromJSON = function(SequencePositionJson) {
      SequencePositionObject <- jsonlite::fromJSON(SequencePositionJson)
      if (!is.null(SequencePositionObject$`reference`)) {
        self$`reference` <- SequencePositionObject$`reference`
      }
      if (!is.null(SequencePositionObject$`position`)) {
        self$`position` <- SequencePositionObject$`position`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "reference": %s,
           "position": %d
        }',
        self$`reference`,
        self$`position`
      )
    },
    fromJSONString = function(SequencePositionJson) {
      SequencePositionObject <- jsonlite::fromJSON(SequencePositionJson)
      self$`reference` <- SequencePositionObject$`reference`
      self$`position` <- SequencePositionObject$`position`
    }
  )
)
