# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SequenceFeature Class
#'
#' @field id 
#' @field label 
#' @field categories 
#' @field types 
#' @field description 
#' @field consider 
#' @field deprecated 
#' @field replaced_by 
#' @field synonyms 
#' @field xrefs 
#' @field taxon 
#' @field locations 
#' @field homology_associations 
#' @field seq 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SequenceFeature <- R6::R6Class(
  'SequenceFeature',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `categories` = NULL,
    `types` = NULL,
    `description` = NULL,
    `consider` = NULL,
    `deprecated` = NULL,
    `replaced_by` = NULL,
    `synonyms` = NULL,
    `xrefs` = NULL,
    `taxon` = NULL,
    `locations` = NULL,
    `homology_associations` = NULL,
    `seq` = NULL,
    initialize = function(`id`, `label`, `categories`, `types`, `description`, `consider`, `deprecated`, `replaced_by`, `synonyms`, `xrefs`, `taxon`, `locations`, `homology_associations`, `seq`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`types`)) {
        stopifnot(is.list(`types`), length(`types`) != 0)
        lapply(`types`, function(x) stopifnot(is.character(x)))
        self$`types` <- `types`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`consider`)) {
        stopifnot(is.list(`consider`), length(`consider`) != 0)
        lapply(`consider`, function(x) stopifnot(is.character(x)))
        self$`consider` <- `consider`
      }
      if (!missing(`deprecated`)) {
        self$`deprecated` <- `deprecated`
      }
      if (!missing(`replaced_by`)) {
        stopifnot(is.list(`replaced_by`), length(`replaced_by`) != 0)
        lapply(`replaced_by`, function(x) stopifnot(is.character(x)))
        self$`replaced_by` <- `replaced_by`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`xrefs`)) {
        stopifnot(is.list(`xrefs`), length(`xrefs`) != 0)
        lapply(`xrefs`, function(x) stopifnot(is.character(x)))
        self$`xrefs` <- `xrefs`
      }
      if (!missing(`taxon`)) {
        stopifnot(R6::is.R6(`taxon`))
        self$`taxon` <- `taxon`
      }
      if (!missing(`locations`)) {
        stopifnot(is.list(`locations`), length(`locations`) != 0)
        lapply(`locations`, function(x) stopifnot(R6::is.R6(x)))
        self$`locations` <- `locations`
      }
      if (!missing(`homology_associations`)) {
        stopifnot(is.list(`homology_associations`), length(`homology_associations`) != 0)
        lapply(`homology_associations`, function(x) stopifnot(R6::is.R6(x)))
        self$`homology_associations` <- `homology_associations`
      }
      if (!missing(`seq`)) {
        stopifnot(R6::is.R6(`seq`))
        self$`seq` <- `seq`
      }
    },
    toJSON = function() {
      SequenceFeatureObject <- list()
      if (!is.null(self$`id`)) {
        SequenceFeatureObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        SequenceFeatureObject[['label']] <- self$`label`
      }
      if (!is.null(self$`categories`)) {
        SequenceFeatureObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`types`)) {
        SequenceFeatureObject[['types']] <- self$`types`
      }
      if (!is.null(self$`description`)) {
        SequenceFeatureObject[['description']] <- self$`description`
      }
      if (!is.null(self$`consider`)) {
        SequenceFeatureObject[['consider']] <- self$`consider`
      }
      if (!is.null(self$`deprecated`)) {
        SequenceFeatureObject[['deprecated']] <- self$`deprecated`
      }
      if (!is.null(self$`replaced_by`)) {
        SequenceFeatureObject[['replaced_by']] <- self$`replaced_by`
      }
      if (!is.null(self$`synonyms`)) {
        SequenceFeatureObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }
      if (!is.null(self$`xrefs`)) {
        SequenceFeatureObject[['xrefs']] <- self$`xrefs`
      }
      if (!is.null(self$`taxon`)) {
        SequenceFeatureObject[['taxon']] <- self$`taxon`$toJSON()
      }
      if (!is.null(self$`locations`)) {
        SequenceFeatureObject[['locations']] <- lapply(self$`locations`, function(x) x$toJSON())
      }
      if (!is.null(self$`homology_associations`)) {
        SequenceFeatureObject[['homology_associations']] <- lapply(self$`homology_associations`, function(x) x$toJSON())
      }
      if (!is.null(self$`seq`)) {
        SequenceFeatureObject[['seq']] <- self$`seq`$toJSON()
      }

      SequenceFeatureObject
    },
    fromJSON = function(SequenceFeatureJson) {
      SequenceFeatureObject <- jsonlite::fromJSON(SequenceFeatureJson)
      if (!is.null(SequenceFeatureObject$`id`)) {
        self$`id` <- SequenceFeatureObject$`id`
      }
      if (!is.null(SequenceFeatureObject$`label`)) {
        self$`label` <- SequenceFeatureObject$`label`
      }
      if (!is.null(SequenceFeatureObject$`categories`)) {
        self$`categories` <- SequenceFeatureObject$`categories`
      }
      if (!is.null(SequenceFeatureObject$`types`)) {
        self$`types` <- SequenceFeatureObject$`types`
      }
      if (!is.null(SequenceFeatureObject$`description`)) {
        self$`description` <- SequenceFeatureObject$`description`
      }
      if (!is.null(SequenceFeatureObject$`consider`)) {
        self$`consider` <- SequenceFeatureObject$`consider`
      }
      if (!is.null(SequenceFeatureObject$`deprecated`)) {
        self$`deprecated` <- SequenceFeatureObject$`deprecated`
      }
      if (!is.null(SequenceFeatureObject$`replaced_by`)) {
        self$`replaced_by` <- SequenceFeatureObject$`replaced_by`
      }
      if (!is.null(SequenceFeatureObject$`synonyms`)) {
        self$`synonyms` <- lapply(SequenceFeatureObject$`synonyms`, function(x) {
          synonymsObject <- SynonymPropertyValue$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
      if (!is.null(SequenceFeatureObject$`xrefs`)) {
        self$`xrefs` <- SequenceFeatureObject$`xrefs`
      }
      if (!is.null(SequenceFeatureObject$`taxon`)) {
        taxonObject <- Taxon$new()
        taxonObject$fromJSON(jsonlite::toJSON(SequenceFeatureObject$taxon, auto_unbox = TRUE))
        self$`taxon` <- taxonObject
      }
      if (!is.null(SequenceFeatureObject$`locations`)) {
        self$`locations` <- lapply(SequenceFeatureObject$`locations`, function(x) {
          locationsObject <- SequenceLocation$new()
          locationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          locationsObject
        })
      }
      if (!is.null(SequenceFeatureObject$`homology_associations`)) {
        self$`homology_associations` <- lapply(SequenceFeatureObject$`homology_associations`, function(x) {
          homology_associationsObject <- Association$new()
          homology_associationsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          homology_associationsObject
        })
      }
      if (!is.null(SequenceFeatureObject$`seq`)) {
        seqObject <- Seq$new()
        seqObject$fromJSON(jsonlite::toJSON(SequenceFeatureObject$seq, auto_unbox = TRUE))
        self$`seq` <- seqObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "categories": [%s],
           "types": [%s],
           "description": %s,
           "consider": [%s],
           "deprecated": %s,
           "replaced_by": [%s],
           "synonyms": [%s],
           "xrefs": [%s],
           "taxon": %s,
           "locations": [%s],
           "homology_associations": [%s],
           "seq": %s
        }',
        self$`id`,
        self$`label`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`types`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        lapply(self$`consider`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`deprecated`,
        lapply(self$`replaced_by`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`xrefs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`taxon`$toJSON(),
        lapply(self$`locations`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`homology_associations`, function(x) paste(x$toJSON(), sep=",")),
        self$`seq`$toJSON()
      )
    },
    fromJSONString = function(SequenceFeatureJson) {
      SequenceFeatureObject <- jsonlite::fromJSON(SequenceFeatureJson)
      self$`id` <- SequenceFeatureObject$`id`
      self$`label` <- SequenceFeatureObject$`label`
      self$`categories` <- SequenceFeatureObject$`categories`
      self$`types` <- SequenceFeatureObject$`types`
      self$`description` <- SequenceFeatureObject$`description`
      self$`consider` <- SequenceFeatureObject$`consider`
      self$`deprecated` <- SequenceFeatureObject$`deprecated`
      self$`replaced_by` <- SequenceFeatureObject$`replaced_by`
      self$`synonyms` <- lapply(SequenceFeatureObject$`synonyms`, function(x) SynonymPropertyValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`xrefs` <- SequenceFeatureObject$`xrefs`
      TaxonObject <- Taxon$new()
      self$`taxon` <- TaxonObject$fromJSON(jsonlite::toJSON(SequenceFeatureObject$taxon, auto_unbox = TRUE))
      self$`locations` <- lapply(SequenceFeatureObject$`locations`, function(x) SequenceLocation$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`homology_associations` <- lapply(SequenceFeatureObject$`homology_associations`, function(x) Association$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      SeqObject <- Seq$new()
      self$`seq` <- SeqObject$fromJSON(jsonlite::toJSON(SequenceFeatureObject$seq, auto_unbox = TRUE))
    }
  )
)
