# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Taxon Class
#'
#' @field id 
#' @field label 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Taxon <- R6::R6Class(
  'Taxon',
  public = list(
    `id` = NULL,
    `label` = NULL,
    initialize = function(`id`, `label`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
    },
    toJSON = function() {
      TaxonObject <- list()
      if (!is.null(self$`id`)) {
        TaxonObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        TaxonObject[['label']] <- self$`label`
      }

      TaxonObject
    },
    fromJSON = function(TaxonJson) {
      TaxonObject <- jsonlite::fromJSON(TaxonJson)
      if (!is.null(TaxonObject$`id`)) {
        self$`id` <- TaxonObject$`id`
      }
      if (!is.null(TaxonObject$`label`)) {
        self$`label` <- TaxonObject$`label`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s
        }',
        self$`id`,
        self$`label`
      )
    },
    fromJSONString = function(TaxonJson) {
      TaxonObject <- jsonlite::fromJSON(TaxonJson)
      self$`id` <- TaxonObject$`id`
      self$`label` <- TaxonObject$`label`
    }
  )
)
