# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Transcript Class
#'
#' @field id 
#' @field label 
#' @field categories 
#' @field types 
#' @field description 
#' @field consider 
#' @field deprecated 
#' @field replaced_by 
#' @field synonyms 
#' @field xrefs 
#' @field taxon 
#' @field exons 
#' @field genes 
#' @field sequence_features 
#' @field cds 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Transcript <- R6::R6Class(
  'Transcript',
  public = list(
    `id` = NULL,
    `label` = NULL,
    `categories` = NULL,
    `types` = NULL,
    `description` = NULL,
    `consider` = NULL,
    `deprecated` = NULL,
    `replaced_by` = NULL,
    `synonyms` = NULL,
    `xrefs` = NULL,
    `taxon` = NULL,
    `exons` = NULL,
    `genes` = NULL,
    `sequence_features` = NULL,
    `cds` = NULL,
    initialize = function(`id`, `label`, `categories`, `types`, `description`, `consider`, `deprecated`, `replaced_by`, `synonyms`, `xrefs`, `taxon`, `exons`, `genes`, `sequence_features`, `cds`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`categories`)) {
        stopifnot(is.list(`categories`), length(`categories`) != 0)
        lapply(`categories`, function(x) stopifnot(is.character(x)))
        self$`categories` <- `categories`
      }
      if (!missing(`types`)) {
        stopifnot(is.list(`types`), length(`types`) != 0)
        lapply(`types`, function(x) stopifnot(is.character(x)))
        self$`types` <- `types`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`consider`)) {
        stopifnot(is.list(`consider`), length(`consider`) != 0)
        lapply(`consider`, function(x) stopifnot(is.character(x)))
        self$`consider` <- `consider`
      }
      if (!missing(`deprecated`)) {
        self$`deprecated` <- `deprecated`
      }
      if (!missing(`replaced_by`)) {
        stopifnot(is.list(`replaced_by`), length(`replaced_by`) != 0)
        lapply(`replaced_by`, function(x) stopifnot(is.character(x)))
        self$`replaced_by` <- `replaced_by`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`xrefs`)) {
        stopifnot(is.list(`xrefs`), length(`xrefs`) != 0)
        lapply(`xrefs`, function(x) stopifnot(is.character(x)))
        self$`xrefs` <- `xrefs`
      }
      if (!missing(`taxon`)) {
        stopifnot(R6::is.R6(`taxon`))
        self$`taxon` <- `taxon`
      }
      if (!missing(`exons`)) {
        stopifnot(is.list(`exons`), length(`exons`) != 0)
        lapply(`exons`, function(x) stopifnot(R6::is.R6(x)))
        self$`exons` <- `exons`
      }
      if (!missing(`genes`)) {
        stopifnot(is.list(`genes`), length(`genes`) != 0)
        lapply(`genes`, function(x) stopifnot(R6::is.R6(x)))
        self$`genes` <- `genes`
      }
      if (!missing(`sequence_features`)) {
        stopifnot(is.list(`sequence_features`), length(`sequence_features`) != 0)
        lapply(`sequence_features`, function(x) stopifnot(R6::is.R6(x)))
        self$`sequence_features` <- `sequence_features`
      }
      if (!missing(`cds`)) {
        stopifnot(is.list(`cds`), length(`cds`) != 0)
        lapply(`cds`, function(x) stopifnot(R6::is.R6(x)))
        self$`cds` <- `cds`
      }
    },
    toJSON = function() {
      TranscriptObject <- list()
      if (!is.null(self$`id`)) {
        TranscriptObject[['id']] <- self$`id`
      }
      if (!is.null(self$`label`)) {
        TranscriptObject[['label']] <- self$`label`
      }
      if (!is.null(self$`categories`)) {
        TranscriptObject[['categories']] <- self$`categories`
      }
      if (!is.null(self$`types`)) {
        TranscriptObject[['types']] <- self$`types`
      }
      if (!is.null(self$`description`)) {
        TranscriptObject[['description']] <- self$`description`
      }
      if (!is.null(self$`consider`)) {
        TranscriptObject[['consider']] <- self$`consider`
      }
      if (!is.null(self$`deprecated`)) {
        TranscriptObject[['deprecated']] <- self$`deprecated`
      }
      if (!is.null(self$`replaced_by`)) {
        TranscriptObject[['replaced_by']] <- self$`replaced_by`
      }
      if (!is.null(self$`synonyms`)) {
        TranscriptObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }
      if (!is.null(self$`xrefs`)) {
        TranscriptObject[['xrefs']] <- self$`xrefs`
      }
      if (!is.null(self$`taxon`)) {
        TranscriptObject[['taxon']] <- self$`taxon`$toJSON()
      }
      if (!is.null(self$`exons`)) {
        TranscriptObject[['exons']] <- lapply(self$`exons`, function(x) x$toJSON())
      }
      if (!is.null(self$`genes`)) {
        TranscriptObject[['genes']] <- lapply(self$`genes`, function(x) x$toJSON())
      }
      if (!is.null(self$`sequence_features`)) {
        TranscriptObject[['sequence_features']] <- lapply(self$`sequence_features`, function(x) x$toJSON())
      }
      if (!is.null(self$`cds`)) {
        TranscriptObject[['cds']] <- lapply(self$`cds`, function(x) x$toJSON())
      }

      TranscriptObject
    },
    fromJSON = function(TranscriptJson) {
      TranscriptObject <- jsonlite::fromJSON(TranscriptJson)
      if (!is.null(TranscriptObject$`id`)) {
        self$`id` <- TranscriptObject$`id`
      }
      if (!is.null(TranscriptObject$`label`)) {
        self$`label` <- TranscriptObject$`label`
      }
      if (!is.null(TranscriptObject$`categories`)) {
        self$`categories` <- TranscriptObject$`categories`
      }
      if (!is.null(TranscriptObject$`types`)) {
        self$`types` <- TranscriptObject$`types`
      }
      if (!is.null(TranscriptObject$`description`)) {
        self$`description` <- TranscriptObject$`description`
      }
      if (!is.null(TranscriptObject$`consider`)) {
        self$`consider` <- TranscriptObject$`consider`
      }
      if (!is.null(TranscriptObject$`deprecated`)) {
        self$`deprecated` <- TranscriptObject$`deprecated`
      }
      if (!is.null(TranscriptObject$`replaced_by`)) {
        self$`replaced_by` <- TranscriptObject$`replaced_by`
      }
      if (!is.null(TranscriptObject$`synonyms`)) {
        self$`synonyms` <- lapply(TranscriptObject$`synonyms`, function(x) {
          synonymsObject <- SynonymPropertyValue$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
      if (!is.null(TranscriptObject$`xrefs`)) {
        self$`xrefs` <- TranscriptObject$`xrefs`
      }
      if (!is.null(TranscriptObject$`taxon`)) {
        taxonObject <- Taxon$new()
        taxonObject$fromJSON(jsonlite::toJSON(TranscriptObject$taxon, auto_unbox = TRUE))
        self$`taxon` <- taxonObject
      }
      if (!is.null(TranscriptObject$`exons`)) {
        self$`exons` <- lapply(TranscriptObject$`exons`, function(x) {
          exonsObject <- Exon$new()
          exonsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          exonsObject
        })
      }
      if (!is.null(TranscriptObject$`genes`)) {
        self$`genes` <- lapply(TranscriptObject$`genes`, function(x) {
          genesObject <- EntityReference$new()
          genesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          genesObject
        })
      }
      if (!is.null(TranscriptObject$`sequence_features`)) {
        self$`sequence_features` <- lapply(TranscriptObject$`sequence_features`, function(x) {
          sequence_featuresObject <- SequenceFeature$new()
          sequence_featuresObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          sequence_featuresObject
        })
      }
      if (!is.null(TranscriptObject$`cds`)) {
        self$`cds` <- lapply(TranscriptObject$`cds`, function(x) {
          cdsObject <- CDS$new()
          cdsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          cdsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "label": %s,
           "categories": [%s],
           "types": [%s],
           "description": %s,
           "consider": [%s],
           "deprecated": %s,
           "replaced_by": [%s],
           "synonyms": [%s],
           "xrefs": [%s],
           "taxon": %s,
           "exons": [%s],
           "genes": [%s],
           "sequence_features": [%s],
           "cds": [%s]
        }',
        self$`id`,
        self$`label`,
        lapply(self$`categories`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`types`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        lapply(self$`consider`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`deprecated`,
        lapply(self$`replaced_by`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`xrefs`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`taxon`$toJSON(),
        lapply(self$`exons`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`genes`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`sequence_features`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`cds`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(TranscriptJson) {
      TranscriptObject <- jsonlite::fromJSON(TranscriptJson)
      self$`id` <- TranscriptObject$`id`
      self$`label` <- TranscriptObject$`label`
      self$`categories` <- TranscriptObject$`categories`
      self$`types` <- TranscriptObject$`types`
      self$`description` <- TranscriptObject$`description`
      self$`consider` <- TranscriptObject$`consider`
      self$`deprecated` <- TranscriptObject$`deprecated`
      self$`replaced_by` <- TranscriptObject$`replaced_by`
      self$`synonyms` <- lapply(TranscriptObject$`synonyms`, function(x) SynonymPropertyValue$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`xrefs` <- TranscriptObject$`xrefs`
      TaxonObject <- Taxon$new()
      self$`taxon` <- TaxonObject$fromJSON(jsonlite::toJSON(TranscriptObject$taxon, auto_unbox = TRUE))
      self$`exons` <- lapply(TranscriptObject$`exons`, function(x) Exon$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`genes` <- lapply(TranscriptObject$`genes`, function(x) EntityReference$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`sequence_features` <- lapply(TranscriptObject$`sequence_features`, function(x) SequenceFeature$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`cds` <- lapply(TranscriptObject$`cds`, function(x) CDS$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
