# BioLink API
#
# API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/
#
# OpenAPI spec version: 0.1.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' VariantSet Class
#'
#' @field body 
#' @field id 
#' @field title 
#' @field category_id 
#' @field pub_date 
#' @field category 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VariantSet <- R6::R6Class(
  'VariantSet',
  public = list(
    `body` = NULL,
    `id` = NULL,
    `title` = NULL,
    `category_id` = NULL,
    `pub_date` = NULL,
    `category` = NULL,
    initialize = function(`body`, `id`, `title`, `category_id`, `pub_date`, `category`){
      if (!missing(`body`)) {
        stopifnot(is.character(`body`), length(`body`) == 1)
        self$`body` <- `body`
      }
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`category_id`)) {
        stopifnot(is.numeric(`category_id`), length(`category_id`) == 1)
        self$`category_id` <- `category_id`
      }
      if (!missing(`pub_date`)) {
        stopifnot(is.character(`pub_date`), length(`pub_date`) == 1)
        self$`pub_date` <- `pub_date`
      }
      if (!missing(`category`)) {
        stopifnot(is.character(`category`), length(`category`) == 1)
        self$`category` <- `category`
      }
    },
    toJSON = function() {
      VariantSetObject <- list()
      if (!is.null(self$`body`)) {
        VariantSetObject[['body']] <- self$`body`
      }
      if (!is.null(self$`id`)) {
        VariantSetObject[['id']] <- self$`id`
      }
      if (!is.null(self$`title`)) {
        VariantSetObject[['title']] <- self$`title`
      }
      if (!is.null(self$`category_id`)) {
        VariantSetObject[['category_id']] <- self$`category_id`
      }
      if (!is.null(self$`pub_date`)) {
        VariantSetObject[['pub_date']] <- self$`pub_date`
      }
      if (!is.null(self$`category`)) {
        VariantSetObject[['category']] <- self$`category`
      }

      VariantSetObject
    },
    fromJSON = function(VariantSetJson) {
      VariantSetObject <- jsonlite::fromJSON(VariantSetJson)
      if (!is.null(VariantSetObject$`body`)) {
        self$`body` <- VariantSetObject$`body`
      }
      if (!is.null(VariantSetObject$`id`)) {
        self$`id` <- VariantSetObject$`id`
      }
      if (!is.null(VariantSetObject$`title`)) {
        self$`title` <- VariantSetObject$`title`
      }
      if (!is.null(VariantSetObject$`category_id`)) {
        self$`category_id` <- VariantSetObject$`category_id`
      }
      if (!is.null(VariantSetObject$`pub_date`)) {
        self$`pub_date` <- VariantSetObject$`pub_date`
      }
      if (!is.null(VariantSetObject$`category`)) {
        self$`category` <- VariantSetObject$`category`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "body": %s,
           "id": %d,
           "title": %s,
           "category_id": %d,
           "pub_date": %s,
           "category": %s
        }',
        self$`body`,
        self$`id`,
        self$`title`,
        self$`category_id`,
        self$`pub_date`,
        self$`category`
      )
    },
    fromJSONString = function(VariantSetJson) {
      VariantSetObject <- jsonlite::fromJSON(VariantSetJson)
      self$`body` <- VariantSetObject$`body`
      self$`id` <- VariantSetObject$`id`
      self$`title` <- VariantSetObject$`title`
      self$`category_id` <- VariantSetObject$`category_id`
      self$`pub_date` <- VariantSetObject$`pub_date`
      self$`category` <- VariantSetObject$`category`
    }
  )
)
